#include "src/game/envfx_snow.h"

const GeoLayout cloud_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ASM(LAYER_OPAQUE, geo_set_global_fog),
		GEO_ASM(LAYER_OPAQUE, geo_set_rain_cloud_prim),
		GEO_SCALE(LAYER_OPAQUE, 6554),
		GEO_OPEN_NODE(),
			GEO_RENDER_RANGE(-2500, 2500),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, cloud_Cloud_mesh_layer_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_SCALE(LAYER_OPAQUE, 6554),
		GEO_OPEN_NODE(),
			GEO_RENDER_RANGE(2500, 5000),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, cloud_CloudLOD_mesh_layer_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_SCALE(LAYER_OPAQUE, 6554),
		GEO_OPEN_NODE(),
			GEO_RENDER_RANGE(5000, 10000),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, cloud_CloudLODDER_mesh_layer_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_SCALE(LAYER_OPAQUE, 6554),
		GEO_OPEN_NODE(),
			GEO_RENDER_RANGE(10000, 20000),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, cloud_CloudLODDEST_mesh_layer_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_SCALE(LAYER_OPAQUE, 6554),
		GEO_OPEN_NODE(),
			GEO_RENDER_RANGE(20000, 30000),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, cloud_CloudLODDESTER_mesh_layer_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ASM(0, geo_update_rain_cloud_rain),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cloud_CloudRain_mesh_layer_5),
		GEO_ASM(0, geo_set_rain_cloud_wind_vis),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cloud_windydangus_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, cloud_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, cloud_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
