extern const GeoLayout rainbow_cloud_switch_opt1[];
extern const GeoLayout rainbow_cloud_geo[];
extern Lights1 rainbow_cloud_Cloud_001_lights;
extern u8 rainbow_cloud_clouds_i8_i8[];
extern u8 rainbow_cloud_open_mouth_face_ia8[];
extern u8 rainbow_cloud_vomitting_face_ia8[];
extern Vtx rainbow_cloud_rdl_mesh_layer_1_vtx_0[29];
extern Gfx rainbow_cloud_rdl_mesh_layer_1_tri_0[];
extern Vtx rainbow_cloud_rdl_mesh_layer_5_vtx_0[4];
extern Gfx rainbow_cloud_rdl_mesh_layer_5_tri_0[];
extern Gfx mat_rainbow_cloud_Cloud_001[];
extern Gfx mat_rainbow_cloud_CloudFace[];
extern Gfx mat_revert_rainbow_cloud_CloudFace[];
extern Gfx mat_rainbow_cloud_CloudFace_001[];
extern Gfx mat_revert_rainbow_cloud_CloudFace_001[];
extern Gfx rainbow_cloud_rdl_mesh_layer_1[];
extern Gfx rainbow_cloud_rdl_mesh_layer_1_mat_override_CloudFace_001_0[];
extern Gfx rainbow_cloud_rdl_mesh_layer_5[];
extern Gfx rainbow_cloud_rdl_mesh_layer_5_mat_override_CloudFace_001_0[];
extern Gfx rainbow_cloud_material_revert_render_settings[];
