extern const GeoLayout laser_ring_spawner_spikes_arm[];
extern const GeoLayout laser_ring_spawner_geo[];
extern Lights1 laser_ring_spawner_Base_lights;
extern Lights1 laser_ring_spawner_Top_lights;
extern Lights1 laser_ring_spawner_spike_lights;
extern u8 laser_ring_spawner_metal_plates_ci8[];
extern u8 laser_ring_spawner_metal_plates_ci8_pal_rgba16[];
extern u8 laser_ring_spawner_top_ci8[];
extern u8 laser_ring_spawner_top_ci8_pal_rgba16[];
extern Vtx laser_ring_spawner_base_mesh_layer_1_vtx_0[30];
extern Gfx laser_ring_spawner_base_mesh_layer_1_tri_0[];
extern Vtx laser_ring_spawner_base_mesh_layer_1_vtx_1[6];
extern Gfx laser_ring_spawner_base_mesh_layer_1_tri_1[];
extern Vtx laser_ring_spawner_top_mesh_layer_1_vtx_0[13];
extern Gfx laser_ring_spawner_top_mesh_layer_1_tri_0[];
extern Vtx laser_ring_spawner_switch_option_spikes_mesh_layer_1_vtx_0[45];
extern Gfx laser_ring_spawner_switch_option_spikes_mesh_layer_1_tri_0[];
extern Gfx mat_laser_ring_spawner_Base[];
extern Gfx mat_revert_laser_ring_spawner_Base[];
extern Gfx mat_laser_ring_spawner_Energy[];
extern Gfx mat_laser_ring_spawner_Top[];
extern Gfx mat_revert_laser_ring_spawner_Top[];
extern Gfx mat_laser_ring_spawner_spike[];
extern Gfx laser_ring_spawner_base_mesh_layer_1[];
extern Gfx laser_ring_spawner_top_mesh_layer_1[];
extern Gfx laser_ring_spawner_switch_option_spikes_mesh_layer_1[];
extern Gfx laser_ring_spawner_material_revert_render_settings[];
