extern const GeoLayout bowser_2_area_1_geo[];
extern const GeoLayout bowser_2_area_1[];
extern const Collision bowser_2_area_1_collision[];
extern const MacroObject bowser_2_area_1_macro_objs[];
extern Lights1 bowser_2_dl_f3d_material_lights;
extern Vtx bowser_2_dl_Plane_001_mesh_layer_1_vtx_cull[8];
extern Vtx bowser_2_dl_Plane_001_mesh_layer_1_vtx_0[4];
extern Gfx bowser_2_dl_Plane_001_mesh_layer_1_tri_0[];
extern Gfx mat_bowser_2_dl_f3d_material[];
extern Gfx bowser_2_dl_Plane_001_mesh_layer_1[];
extern Gfx bowser_2_dl_material_revert_render_settings[];
