extern const GeoLayout bowser_2_area_1_geo[];
extern const GeoLayout bowser_2_area_1[];
extern const Collision bowser_2_area_1_collision[];
extern const MacroObject bowser_2_area_1_macro_objs[];
extern u8 bowser_2_dl_snowtrees_rgba16[];
extern u8 bowser_2_dl_krtd_ice_floor_ci4[];
extern u8 bowser_2_dl_krtd_ice_floor_ci4_pal_rgba16[];
extern Vtx bowser_2_dl_col_mesh_layer_4_vtx_cull[8];
extern Vtx bowser_2_dl_col_mesh_layer_4_vtx_0[82];
extern Gfx bowser_2_dl_col_mesh_layer_4_tri_0[];
extern Vtx bowser_2_dl_col_mesh_layer_1_vtx_cull[8];
extern Vtx bowser_2_dl_col_mesh_layer_1_vtx_0[116];
extern Gfx bowser_2_dl_col_mesh_layer_1_tri_0[];
extern Gfx mat_bowser_2_dl_trees_002[];
extern Gfx mat_revert_bowser_2_dl_trees_002[];
extern Gfx mat_bowser_2_dl_snow_002[];
extern Gfx mat_revert_bowser_2_dl_snow_002[];
extern Gfx bowser_2_dl_col_mesh_layer_4[];
extern Gfx bowser_2_dl_col_mesh_layer_1[];
extern Gfx bowser_2_dl_material_revert_render_settings[];
