extern const GeoLayout bowser_2_area_1_geo[];
extern const GeoLayout bowser_2_area_1[];
extern const Collision bowser_2_area_1_collision[];
extern const MacroObject bowser_2_area_1_macro_objs[];
extern u8 bowser_2_dl_krtd_ice_floor_ci4[];
extern u8 bowser_2_dl_krtd_ice_floor_ci4_pal_rgba16[];
extern u8 bowser_2_dl_snowtrees_rgba16[];
extern Vtx bowser_2_dl_Plane_mesh_layer_5_vtx_cull[8];
extern Vtx bowser_2_dl_Plane_mesh_layer_5_vtx_0[8];
extern Gfx bowser_2_dl_Plane_mesh_layer_5_tri_0[];
extern Vtx bowser_2_dl_Plane_mesh_layer_5_vtx_1[16];
extern Gfx bowser_2_dl_Plane_mesh_layer_5_tri_1[];
extern Gfx mat_bowser_2_dl_snow_001[];
extern Gfx mat_revert_bowser_2_dl_snow_001[];
extern Gfx mat_bowser_2_dl_trees_001[];
extern Gfx mat_revert_bowser_2_dl_trees_001[];
extern Gfx bowser_2_dl_Plane_mesh_layer_5[];
extern Gfx bowser_2_dl_material_revert_render_settings[];
