extern const GeoLayout elevator_geo[];
extern Lights1 elevator_nothing_f3d_v4_001_lights;
extern Vtx elevator__THE_actual_elevator_mesh_layer_1_vtx_0[40];
extern Gfx elevator__THE_actual_elevator_mesh_layer_1_tri_0[];
extern Vtx elevator__THE_actual_elevator_mesh_layer_5_vtx_0[60];
extern Gfx elevator__THE_actual_elevator_mesh_layer_5_tri_0[];
extern Gfx mat_elevator_nothing_f3d_v4_001[];
extern Gfx mat_revert_elevator_nothing_f3d_v4_001[];
extern Gfx mat_elevator_absolutely_nothing[];
extern Gfx elevator__THE_actual_elevator_mesh_layer_1[];
extern Gfx elevator__THE_actual_elevator_mesh_layer_5[];
extern Gfx elevator_material_revert_render_settings[];
