extern const GeoLayout rainbow_star_geo[];
extern Lights1 rainbow_star_f3d_material_lights;
extern Lights1 rainbow_star_f3d_material_001_lights;
extern u8 rainbow_star_Rainbow_small_ci8[];
extern u8 rainbow_star_Rainbow_small_ci8_pal_rgba16[];
extern u8 rainbow_star_star_eye_rgba16_rgba16[];
extern Vtx rainbow_star_000_displaylist_mesh_layer_1_vtx_0[12];
extern Gfx rainbow_star_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx rainbow_star_001_displaylist_mesh_layer_5_vtx_0[6];
extern Gfx rainbow_star_001_displaylist_mesh_layer_5_tri_0[];
extern Gfx mat_rainbow_star_f3d_material[];
extern Gfx mat_revert_rainbow_star_f3d_material[];
extern Gfx mat_rainbow_star_f3d_material_001[];
extern Gfx rainbow_star_000_displaylist_mesh_layer_1[];
extern Gfx rainbow_star_001_displaylist_mesh_layer_5[];
extern Gfx rainbow_star_material_revert_render_settings[];
