extern const GeoLayout simple_spinner_shock_geo[];
extern Lights1 simple_spinner_shock_f3d_material_lights;
extern Vtx simple_spinner_shock_000_displaylist_mesh_layer_1_vtx_0[57];
extern Gfx simple_spinner_shock_000_displaylist_mesh_layer_1_tri_0[];
extern Gfx mat_simple_spinner_shock_f3d_material[];
extern Gfx simple_spinner_shock_000_displaylist_mesh_layer_1[];
extern Gfx simple_spinner_shock_material_revert_render_settings[];
