extern const GeoLayout dirt_patch_geo[];
extern Lights1 dirt_patch_f3dlite_material_004_lights;
extern u8 dirt_patch_bigthorn_ci4[];
extern u8 dirt_patch_bigthorn_ci4_pal_rgba16[];
extern Vtx dirt_patch_Circle_001_mesh_layer_1_vtx_cull[8];
extern Vtx dirt_patch_Circle_001_mesh_layer_1_vtx_0[12];
extern Gfx dirt_patch_Circle_001_mesh_layer_1_tri_0[];
extern Gfx mat_dirt_patch_f3dlite_material_004[];
extern Gfx mat_revert_dirt_patch_f3dlite_material_004[];
extern Gfx dirt_patch_Circle_001_mesh_layer_1[];
extern Gfx dirt_patch_material_revert_render_settings[];
