extern const GeoLayout bowser_1_area_1_geo[];
extern const GeoLayout bowser_1_area_1[];
extern const Collision bowser_1_area_1_collision[];
extern const MacroObject bowser_1_area_1_macro_objs[];
extern Lights0 bowser_1_dl_cozieswater_top_emu__layer5_lights;
extern u8 bowser_1_dl_Rainbow_small_rgba16[];
extern u8 bowser_1_dl__3623064_32_grey_i8[];
extern u8 bowser_1_dl_scrolling_texture_ci4[];
extern u8 bowser_1_dl_scrolling_texture_ci4_pal_rgba16[];
extern u8 bowser_1_dl_water_big_chungus_defined_intensity2_i4[];
extern Vtx bowser_1_dl_Torus_mesh_layer_1_vtx_cull[8];
extern Vtx bowser_1_dl_Torus_mesh_layer_1_vtx_0[192];
extern Gfx bowser_1_dl_Torus_mesh_layer_1_tri_0[];
extern Vtx bowser_1_dl_Torus_mesh_layer_1_vtx_1[9];
extern Gfx bowser_1_dl_Torus_mesh_layer_1_tri_1[];
extern Vtx bowser_1_dl_Torus_mesh_layer_5_vtx_cull[8];
extern Vtx bowser_1_dl_Torus_mesh_layer_5_vtx_0[528];
extern Gfx bowser_1_dl_Torus_mesh_layer_5_tri_0[];
extern Gfx mat_bowser_1_dl_f3d_material_layer1[];
extern Gfx mat_revert_bowser_1_dl_f3d_material_layer1[];
extern Gfx mat_bowser_1_dl_vein_rock[];
extern Gfx mat_revert_bowser_1_dl_vein_rock[];
extern Gfx mat_bowser_1_dl_cozieswater_top_emu__layer5[];
extern Gfx mat_revert_bowser_1_dl_cozieswater_top_emu__layer5[];
extern Gfx bowser_1_dl_Torus_mesh_layer_1[];
extern Gfx bowser_1_dl_Torus_mesh_layer_5[];
extern Gfx bowser_1_dl_material_revert_render_settings[];
