#include <ultra64.h>"
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "level_misc_macros.h"
#include "macro_preset_names.h"
#include "special_preset_names.h"
#include "textures.h"
#include "dialog_ids.h"

#include "make_const_nonconst.h"


#include "levels/bowser_1/leveldata.inc.c"

#include "levels/bowser_1/cage/model.inc.c"
#include "levels/bowser_1/cage/collision.inc.c"
#include "levels/bowser_1/ashpile/model.inc.c"
#include "levels/bowser_1/ashpile2/model.inc.c"
#include "levels/bowser_1/ashpile2/collision.inc.c"
#include "levels/bowser_1/ashpile/collision.inc.c"
#include "levels/bowser_1/electric_ring/collision.inc.c"
#include "levels/bowser_1/electric_ring/model.inc.c"
#include "levels/bowser_1/laser_ring/model.inc.c"
#include "levels/bowser_1/circle/model.inc.c"
#include "levels/bowser_1/lightning/model.inc.c"