extern const GeoLayout clown_door_bottom_geo[];
extern Lights1 clown_door_bottom_f3d_material_032_lights;
extern u8 clown_door_bottom_clown_bottom_ci8[];
extern u8 clown_door_bottom_clown_bottom_ci8_pal_rgba16[];
extern Vtx clown_door_bottom_Cube_004_mesh_layer_1_vtx_0[24];
extern Gfx clown_door_bottom_Cube_004_mesh_layer_1_tri_0[];
extern Gfx mat_clown_door_bottom_f3d_material_032[];
extern Gfx mat_revert_clown_door_bottom_f3d_material_032[];
extern Gfx clown_door_bottom_Cube_004_mesh_layer_1[];
extern Gfx clown_door_bottom_material_revert_render_settings[];
