extern const GeoLayout sad_clown_clock_geo[];
extern Lights1 sad_clown_clock_f3d_material_119_lights;
extern Lights1 sad_clown_clock_f3d_material_029_lights;
extern u8 sad_clown_clock_glove_i8[];
extern u8 sad_clown_clock_sadcarosuelplanks_ci4[];
extern u8 sad_clown_clock_sadcarosuelplanks_ci4_pal_rgba16[];
extern Vtx sad_clown_clock_Cube_065_mesh_layer_1_vtx_0[325];
extern Gfx sad_clown_clock_Cube_065_mesh_layer_1_tri_0[];
extern Vtx sad_clown_clock_Cube_065_mesh_layer_1_vtx_1[416];
extern Gfx sad_clown_clock_Cube_065_mesh_layer_1_tri_1[];
extern Gfx mat_sad_clown_clock_f3d_material_119[];
extern Gfx mat_sad_clown_clock_f3d_material_029[];
extern Gfx mat_revert_sad_clown_clock_f3d_material_029[];
extern Gfx sad_clown_clock_Cube_065_mesh_layer_1[];
extern Gfx sad_clown_clock_material_revert_render_settings[];
