extern const GeoLayout cheezebombwall_geo[];
extern Lights1 cheezebombwall_fortress_lights;
extern Lights1 cheezebombwall_crack_lights;
extern u8 cheezebombwall_Bctrwi3_wall2_comp_i4[];
extern u8 cheezebombwall_crack_ia8[];
extern Vtx cheezebombwall_bomb1_mesh_layer_1_vtx_cull[8];
extern Vtx cheezebombwall_bomb1_mesh_layer_1_vtx_0[10];
extern Gfx cheezebombwall_bomb1_mesh_layer_1_tri_0[];
extern Vtx cheezebombwall_bomb1_mesh_layer_6_vtx_cull[8];
extern Vtx cheezebombwall_bomb1_mesh_layer_6_vtx_0[4];
extern Gfx cheezebombwall_bomb1_mesh_layer_6_tri_0[];
extern Gfx mat_cheezebombwall_fortress[];
extern Gfx mat_cheezebombwall_crack[];
extern Gfx cheezebombwall_bomb1_mesh_layer_1[];
extern Gfx cheezebombwall_bomb1_mesh_layer_6[];
extern Gfx cheezebombwall_material_revert_render_settings[];
