#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "game/level_geo.h"
#include "game/geo_misc.h"
#include "game/camera.h"
#include "game/moving_texture.h"
#include "game/screen_transition.h"
#include "game/paintings.h"

#include "make_const_nonconst.h"

#include "levels/ccm/header.h"

#include "levels/ccm/ropeway_lift/geo.inc.c"
#include "levels/ccm/snowman_base/geo.inc.c"
#include "levels/ccm/snowman_head/geo.inc.c"
#include "levels/ccm/areas/1/6/geo.inc.c"
#include "levels/ccm/areas/1/7/geo.inc.c"
#include "levels/ccm/areas/1/8/geo.inc.c"
#include "levels/ccm/areas/1/9/geo.inc.c"
#include "levels/ccm/areas/1/10/geo.inc.c"
#include "levels/ccm/areas/1/geo.inc.c"
#include "levels/ccm/areas/2/geo.inc.c"
#include "levels/ccm/geo.inc.c"

#include "levels/ccm/magma_thwomp/geo.inc.c"
#include "levels/ccm/swing_board/geo.inc.c"
#include "levels/ccm/propane_thrower/geo.inc.c"
#include "levels/ccm/lava_grate/geo.inc.c"
#include "levels/ccm/castle_raft/geo.inc.c"
#include "levels/ccm/ashpile/geo.inc.c"
#include "levels/ccm/ashpile2/geo.inc.c"
#include "levels/ccm/rovert_elevator/geo.inc.c"
#include "levels/ccm/rovert_fling/geo.inc.c"
#include "levels/ccm/toad_cage_1_geo/geo.inc.c"
#include "levels/ccm/toad_cage_2_geo/geo.inc.c"
#include "levels/ccm/toad_cage_3_geo/geo.inc.c"
#include "levels/ccm/toad_cage_4_geo/geo.inc.c"
#include "levels/ccm/tank_base/geo.inc.c"
#include "levels/ccm/tank_head/geo.inc.c"
#include "levels/ccm/rmine/geo.inc.c"
#include "levels/ccm/missile/geo.inc.c"