extern const GeoLayout lightning_cloud_switch_opt1[];
extern const GeoLayout lightning_cloud_geo[];
extern Lights1 lightning_cloud_Cloud_001_lights;
extern u8 lightning_cloud_clouds_i8_i8[];
extern u8 lightning_cloud_angry_open_mouth_face_ia8[];
extern u8 lightning_cloud_vomitting_face_ia8[];
extern Vtx lightning_cloud_rdl_mesh_layer_1_vtx_0[29];
extern Gfx lightning_cloud_rdl_mesh_layer_1_tri_0[];
extern Vtx lightning_cloud_rdl_mesh_layer_5_vtx_0[4];
extern Gfx lightning_cloud_rdl_mesh_layer_5_tri_0[];
extern Gfx mat_lightning_cloud_Cloud_001[];
extern Gfx mat_lightning_cloud_CloudFaceLightning[];
extern Gfx mat_revert_lightning_cloud_CloudFaceLightning[];
extern Gfx mat_lightning_cloud_CloudFace_001[];
extern Gfx mat_revert_lightning_cloud_CloudFace_001[];
extern Gfx lightning_cloud_rdl_mesh_layer_1[];
extern Gfx lightning_cloud_rdl_mesh_layer_1_mat_override_CloudFace_001_0[];
extern Gfx lightning_cloud_rdl_mesh_layer_5[];
extern Gfx lightning_cloud_rdl_mesh_layer_5_mat_override_CloudFace_001_0[];
extern Gfx lightning_cloud_material_revert_render_settings[];
