extern void scroll_castle_grounds_dl_Sphere_mesh_layer_1_vtx_6();
extern void scroll_castle_grounds_dl_Sphere_mesh_layer_1_vtx_53();
extern void scroll_sts_mat_castle_grounds_dl_f3d_material_036();
extern void scroll_sts_mat_castle_grounds_dl_f3d_material_034();
extern void scroll_sts_mat_castle_grounds_dl_electricity_layer5();
extern void scroll_sts_mat_castle_grounds_dl_cozieswater_top_emu__layer5();
extern void scroll_castle_grounds();
