#include "src/game/envfx_snow.h"

const GeoLayout ddd_area_3_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ASM(LAYER_OPAQUE_INTER, geo_set_global_fog),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_INTER, ddd_dl_NZRockWalls_mesh_layer_3),
		GEO_ASM(LAYER_OPAQUE_INTER, geo_set_global_fog),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_INTER, ddd_dl_NZRockWalls_002_mesh_layer_3),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -13488, -7621, -2599),
		GEO_OPEN_NODE(),
			GEO_ASM(LAYER_OPAQUE, geo_set_global_fog),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_spoutpillar_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -11125, -7621, -3206),
		GEO_OPEN_NODE(),
			GEO_ASM(LAYER_OPAQUE, geo_set_global_fog),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_spoutpillar_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -20000, 6000, 0),
		GEO_OPEN_NODE(),
			GEO_ASM(LAYER_OPAQUE_INTER, geo_set_global_fog),
			GEO_DISPLAY_LIST(LAYER_OPAQUE_INTER, ddd_dl_TubeToArea3_mesh_layer_3),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_INTER, ddd_dl_ZAguaFall_mesh_layer_3),
		GEO_ASM(LAYER_OPAQUE_INTER, geo_set_global_fog),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_INTER, ddd_dl_ZRockWalls_mesh_layer_3),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_INTER, ddd_dl_ZZZZWaterBottom_mesh_layer_3),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT_INTER, 0, 1155, 0, ddd_dl_ZZZZWaterBottomFoggg_mesh_layer_7),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT_DECAL, 0, 1155, 0, ddd_dl_ZZZZWaterFallExtraFog_mesh_layer_6),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout ddd_area_3[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 40000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 20000, -10000, 0, 20000, -10100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, ddd_area_3_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_SNOW_WATER, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_INTER, ddd_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, ddd_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_INTER, ddd_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
