#include "src/game/envfx_snow.h"

const GeoLayout hmc_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(3, geo_switch_area),
		GEO_OPEN_NODE(),
			GEO_BRANCH(1, hmc_dl_Area_1_Room_1_geo),
			GEO_BRANCH(1, hmc_dl_Area_1_Room_2_geo),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout hmc_dl_Area_1_Room_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(4, 484, 1380, -463, hmc_dl_Background_mesh_layer_4),
		GEO_TRANSLATE_NODE_WITH_DL(1, 1784, 883, 1062, hmc_dl_Bell_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 122, 406, 1871, hmc_dl_Bell_001_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 1277, 1895, -2174, hmc_dl_Bell_002_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 2474, 1699, -1846, hmc_dl_Bell_003_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 1219, 1500, -2140, hmc_dl_Bellpost_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 393, 2036, -284, hmc_dl_House_Exterior_mesh_layer_1),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 1340, 76, 2620),
		GEO_OPEN_NODE(),
			GEO_RENDER_RANGE(-1000, 2000),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_render_mirror_mario),
				GEO_DISPLAY_LIST(5, hmc_dl_Lake_HD_mesh_layer_5),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 1370, 76, 2690),
		GEO_OPEN_NODE(),
			GEO_RENDER_RANGE(2000, 30000),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(1, hmc_dl_Lake_LD_mesh_layer_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 1340, 76, 2620),
		GEO_OPEN_NODE(),
			GEO_RENDER_RANGE(-1000, 2000),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(1, hmc_dl_Lake_Reflection_mesh_layer_1),
				GEO_DISPLAY_LIST(4, hmc_dl_Lake_Reflection_mesh_layer_4),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(1, -1797, 133, -2276, hmc_dl_Large_Rock_A_001_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 3012, 159, -323, hmc_dl_Large_Rock_A_008_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 368, 1612, -713, hmc_dl_Large_Rock_A_009_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, -1684, 70, 2579, hmc_dl_Large_Rock_B_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 398, 0, -435, hmc_dl_Plane_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 3430, 80, -924, hmc_dl_Small_Rocks_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, -1326, 3, 1673, hmc_dl_Small_Rocks_001_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, -132, 152, -3031, hmc_dl_Small_Rocks_002_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 834, 1502, -636, hmc_dl_Small_Rocks_003_mesh_layer_1),
		GEO_DISPLAY_LIST(1, hmc_dl_Tree_Model_mesh_layer_1),
		GEO_DISPLAY_LIST(4, hmc_dl_Tree_Model_mesh_layer_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout hmc_dl_Area_1_Room_2_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(1, -119, 1559, -248, hmc_dl_Coffee_Table_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 908, 1488, -40, hmc_dl_Elevator_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(5, 341, 1619, -682, hmc_dl_God_Rays_003_mesh_layer_5),
		GEO_TRANSLATE_NODE_WITH_DL(1, 455, 1793, -259, hmc_dl_House_Interior_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout hmc_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0x94A5),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -1000, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, hmc_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_SNOW_BLIZZARD, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(5, hmc_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, hmc_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, hmc_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
