extern const GeoLayout propane_thrower_bits_geo[];
extern Lights1 propane_thrower_bits_black_lights;
extern u8 propane_thrower_bits_rgba16_anonmoose_envmap_silver1_i8[];
extern Vtx propane_thrower_bits_Cylinder_mesh_layer_1_vtx_cull[8];
extern Vtx propane_thrower_bits_Cylinder_mesh_layer_1_vtx_0[42];
extern Gfx propane_thrower_bits_Cylinder_mesh_layer_1_tri_0[];
extern Vtx propane_thrower_bits_Cylinder_mesh_layer_1_vtx_1[12];
extern Gfx propane_thrower_bits_Cylinder_mesh_layer_1_tri_1[];
extern Gfx mat_propane_thrower_bits_metal[];
extern Gfx mat_revert_propane_thrower_bits_metal[];
extern Gfx mat_propane_thrower_bits_black[];
extern Gfx propane_thrower_bits_Cylinder_mesh_layer_1[];
extern Gfx propane_thrower_bits_material_revert_render_settings[];
