extern const GeoLayout sl_area_1_geo[];
extern const GeoLayout sl_area_1[];
extern const Collision sl_area_1_collision[];
extern const MacroObject sl_area_1_macro_objs[];
extern Lights1 sl_dl_Logs_layer1_lights;
extern Lights1 sl_dl_Metal_layer1_lights;
extern Lights1 sl_dl_Planks_layer1_lights;
extern u8 sl_dl_logscolor_rgba16[];
extern u8 sl_dl_logsvalue_i4[];
extern u8 sl_dl_metalcolor_rgba16[];
extern u8 sl_dl_metalvalue_i4[];
extern u8 sl_dl_plankscolor_rgba16[];
extern u8 sl_dl_planksvalue_i4[];
extern Vtx sl_dl_Board_Rounds_mesh_layer_1_vtx_cull[8];
extern Vtx sl_dl_Board_Rounds_mesh_layer_1_vtx_0[100];
extern Gfx sl_dl_Board_Rounds_mesh_layer_1_tri_0[];
extern Vtx sl_dl_Boards_mesh_layer_1_vtx_cull[8];
extern Vtx sl_dl_Boards_mesh_layer_1_vtx_0[308];
extern Gfx sl_dl_Boards_mesh_layer_1_tri_0[];
extern Vtx sl_dl_House_mesh_layer_1_vtx_cull[8];
extern Vtx sl_dl_House_mesh_layer_1_vtx_0[54];
extern Gfx sl_dl_House_mesh_layer_1_tri_0[];
extern Vtx sl_dl_House_mesh_layer_1_vtx_1[223];
extern Gfx sl_dl_House_mesh_layer_1_tri_1[];
extern Vtx sl_dl_House_mesh_layer_1_vtx_2[58];
extern Gfx sl_dl_House_mesh_layer_1_tri_2[];
extern Vtx sl_dl_Water_Bottom_Visual_mesh_layer_5_vtx_cull[8];
extern Vtx sl_dl_Water_Bottom_Visual_mesh_layer_5_vtx_0[25];
extern Gfx sl_dl_Water_Bottom_Visual_mesh_layer_5_tri_0[];
extern Gfx mat_sl_dl_Logs_layer1[];
extern Gfx mat_revert_sl_dl_Logs_layer1[];
extern Gfx mat_sl_dl_Metal_layer1[];
extern Gfx mat_revert_sl_dl_Metal_layer1[];
extern Gfx mat_sl_dl_Planks_layer1[];
extern Gfx mat_revert_sl_dl_Planks_layer1[];
extern Gfx mat_sl_dl_Water_Bottom[];
extern Gfx mat_revert_sl_dl_Water_Bottom[];
extern Gfx sl_dl_Board_Rounds_mesh_layer_1[];
extern Gfx sl_dl_Boards_mesh_layer_1[];
extern Gfx sl_dl_House_mesh_layer_1[];
extern Gfx sl_dl_Water_Bottom_Visual_mesh_layer_5[];
extern Gfx sl_dl_material_revert_render_settings[];
