extern const GeoLayout sl_area_1_geo[];
extern const GeoLayout sl_area_1[];
extern const Collision sl_area_1_collision[];
extern const MacroObject sl_area_1_macro_objs[];
extern Lights1 sl_dl_sm64_material_lights;
extern Vtx sl_dl_Cube_mesh_vtx_cull[8];
extern Vtx sl_dl_Cube_mesh_vtx_0[24];
extern Gfx sl_dl_Cube_mesh_tri_0[];
extern Vtx sl_dl_Water_Bottom_mesh_layer_5_vtx_cull[8];
extern Vtx sl_dl_Water_Bottom_mesh_layer_5_vtx_0[4];
extern Gfx sl_dl_Water_Bottom_mesh_layer_5_tri_0[];
extern Gfx mat_sl_dl_sm64_material[];
extern Gfx mat_sl_dl_Water_Bottom[];
extern Gfx mat_revert_sl_dl_Water_Bottom[];
extern Gfx sl_dl_Cube_mesh[];
extern Gfx sl_dl_Water_Bottom_mesh_layer_5[];
extern Gfx sl_dl_material_revert_render_settings[];
