#include "src/game/envfx_snow.h"

const GeoLayout lll_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, lll_dl_A1_castle_wall_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, lll_dl_A2_roof_windows_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, lll_dl_A3_bottom_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, lll_dl_B1_wall_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, lll_dl_B2_wall_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, lll_dl_D1_over_E1_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, lll_dl_D2_windows_doors_decal_mesh_layer_2),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, lll_dl_E1_city_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, lll_dl_E1_city_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, lll_dl_E10_tree_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, lll_dl_E11_right_costal_wall1_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, lll_dl_E2_above_water_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, lll_dl_E3_right_platforms_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, lll_dl_E4_courtyard_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, lll_dl_E5_left_platforms_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, lll_dl_E6_crate_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, lll_dl_E7_court_bridge_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, lll_dl_E8_court_bridge_rope_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, lll_dl_E9_leaf_shadow_mesh_layer_6),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, lll_dl_flower_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, lll_dl_fountain_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, lll_dl_fountain_water_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, lll_dl_Grass_Decal_mesh_layer_6),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, lll_dl_Mud_Vis_mesh_layer_2),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, lll_dl_Mud_Vis_001_mesh_layer_2),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, lll_dl_platforms_006_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, lll_dl_pole_vis_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, lll_dl_Shadow_mesh_layer_6),
		GEO_ROTATION_NODE_WITH_DL(LAYER_OPAQUE, 90, 0, 0, lll_dl_statue_vis_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, lll_dl_Y1_grass_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, lll_dl_Y2_lake_wall_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, lll_dl_Y3_wall_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, lll_dl_Y4_water_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, lll_dl_Y5_underneath1_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, lll_dl_Y6_underneath2_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, lll_dl_ZZ1_tree_mountain_wall_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, lll_dl_ZZ2_Cloud_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_FORCE, lll_dl_ZZ3_skybox_mesh_layer_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout lll_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 120000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, lll_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_FORCE, lll_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, lll_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_DECAL, lll_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, lll_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, lll_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, lll_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
