#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "make_const_nonconst.h"

#include "common1.h"
#include "group0.h"

#include "bubble/geo.inc.c"
#include "walk_smoke/geo.inc.c"
#include "burn_smoke/geo.inc.c"
#include "stomp_smoke/geo.inc.c"
#include "water_wave/geo.inc.c"
#include "sparkle/geo.inc.c"
#include "water_splash/geo.inc.c"
#include "sparkle_animation/geo.inc.c"
#include "mario/geo.inc.c"

#include "dog/geo.inc.c"

#include "rex/geo.inc.c"
#include "galoomba/geo.inc.c"
#include "blooper/geo.inc.c"
#include "blargg/geo.inc.c"
#include "buzzy_beetle/geo.inc.c"
#include "nipper/geo.inc.c"
#include "cleft/geo.inc.c"
#include "motos/geo.inc.c"
#include "strollin_stu/geo.inc.c"
#include "laser_ring_spawner/geo.inc.c"
#include "laser_ring/geo.inc.c"
#include "spike/geo.inc.c"
#include "spike_ball/geo.inc.c"
#include "podoboo/geo.inc.c"
#include "cephie/geo.inc.c"
#include "koopatrol/geo.inc.c"