#include "src/game/envfx_snow.h"

const GeoLayout bbh_area_3_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(2, geo_switch_area),
		GEO_OPEN_NODE(),
			GEO_BRANCH(1, bbh_dl_31__Boss_geo),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -65534, 0, 0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bbh_dl_31__Boss_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, -65534, 0, 0),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -65534, 0, 0, bbh_dl_CenterPlat_002_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -65534, 0, 0, bbh_dl_CenterPlat_003_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -65534, 0, 0, bbh_dl_CenterPlat_004_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -65534, 0, 0, bbh_dl_CenterPlat_005_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -65534, 0, 0, bbh_dl_CenterPlat_006_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 65534, 0, 0, bbh_dl_CloudIsland3_001_mesh_layer_1),
			GEO_TRANSLATE_NODE(LAYER_OPAQUE, -65534, 0, 0),
			GEO_OPEN_NODE(),
				GEO_ASM(1, geo_comit_cpu_fog),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_GenericCloudPlat_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE(LAYER_OPAQUE, -65534, 0, 0),
			GEO_OPEN_NODE(),
				GEO_ASM(1, geo_comit_cpu_fog),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_GenericCloudPlat_003_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE(LAYER_OPAQUE, -65534, 0, 0),
			GEO_OPEN_NODE(),
				GEO_ASM(1, geo_comit_cpu_fog),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE(LAYER_OPAQUE, -65534, 0, 0),
			GEO_OPEN_NODE(),
				GEO_ASM(1, geo_comit_cpu_fog),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_GenericCloudPlats5_003_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE(LAYER_OPAQUE, -65534, 0, 0),
			GEO_OPEN_NODE(),
				GEO_ASM(1, geo_comit_cpu_fog),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_GenericCloudPlats5_004_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE(LAYER_OPAQUE, -65534, 0, 0),
			GEO_OPEN_NODE(),
				GEO_ASM(1, geo_comit_cpu_fog),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_GenericCloudPlats5_005_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE(LAYER_OPAQUE, -65534, 0, 0),
			GEO_OPEN_NODE(),
				GEO_ASM(1, geo_comit_cpu_fog),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_GenericCloudPlats5_006_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE(LAYER_OPAQUE, -65534, 0, 0),
			GEO_OPEN_NODE(),
				GEO_ASM(1, geo_comit_cpu_fog),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_GenericCloudPlats5_007_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE(LAYER_OPAQUE, -65534, 0, 0),
			GEO_OPEN_NODE(),
				GEO_ASM(1, geo_comit_cpu_fog),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_GenericCloudPlats5_008_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE(LAYER_OPAQUE, -65534, 0, 0),
			GEO_OPEN_NODE(),
				GEO_ASM(1, geo_comit_cpu_fog),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_GenericCloudPlats5_009_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE(LAYER_OPAQUE, -65534, 0, 0),
			GEO_OPEN_NODE(),
				GEO_ASM(1, geo_comit_cpu_fog),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_GenericCloudPlats5_010_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE(LAYER_OPAQUE, -65534, 0, 0),
			GEO_OPEN_NODE(),
				GEO_ASM(1, geo_comit_cpu_fog),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_GenericCloudPlats5_011_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE(LAYER_OPAQUE, -65534, 0, 0),
			GEO_OPEN_NODE(),
				GEO_ASM(1, geo_comit_cpu_fog),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_GenericCloudPlats5_012_mesh_layer_1),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 65534, 0, 0, bbh_dl_YBuilding_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 65534, 0, 0, bbh_dl_YBuilding_001_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 65534, 0, 0, bbh_dl_YBuilding_002_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 65534, 0, 0, bbh_dl_YBuilding_003_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 65534, 0, 0, bbh_dl_YBuilding_004_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 65534, 0, 0, bbh_dl_YBuilding_005_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 65534, 0, 0, bbh_dl_YBuilding_006_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 65534, 0, 0, bbh_dl_YBuilding_007_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 65534, 0, 0, bbh_dl_YBuilding_008_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 65534, 0, 0, bbh_dl_YBuilding_009_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 65534, 0, 0, bbh_dl_YBuilding_010_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 65534, 0, 0, bbh_dl_YBuilding_011_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 65534, 0, 0, bbh_dl_ZBuilding_001_mesh_layer_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bbh_area_3[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 106, 32000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 131068, 0, 0, 131068, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, bbh_area_3_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
