#include "levels/bits/area_7/geo.inc.c"
#include "levels/bits/area_4/geo.inc.c"
#include "levels/bits/area_1/geo.inc.c"
#include "levels/bits/area_6/geo.inc.c"
#include "levels/bits/area_8/geo.inc.c"
#include "levels/bits/area_2/geo.inc.c"
#include "levels/bits/area_3/geo.inc.c"
#include "levels/bits/area_5/geo.inc.c"
