extern const GeoLayout jetski_geo[];
extern Lights1 jetski_doggard_f3d_lights;
extern u8 jetski_doggard_ci4[];
extern u8 jetski_doggard_ci4_pal_rgba16[];
extern Vtx jetski_000_displaylist_mesh_layer_1_vtx_0[114];
extern Gfx jetski_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx jetski_head_mesh_layer_1_vtx_0[34];
extern Gfx jetski_head_mesh_layer_1_tri_0[];
extern Vtx jetski_tail_mesh_layer_1_vtx_0[12];
extern Gfx jetski_tail_mesh_layer_1_tri_0[];
extern Gfx mat_jetski_doggard_f3d[];
extern Gfx mat_revert_jetski_doggard_f3d[];
extern Gfx jetski_000_displaylist_mesh_layer_1[];
extern Gfx jetski_head_mesh_layer_1[];
extern Gfx jetski_tail_mesh_layer_1[];
extern Gfx jetski_material_revert_render_settings[];
