#include "src/game/envfx_snow.h"

const GeoLayout koopa_npc_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_BONE(LAYER_TRANSPARENT_DECAL, 0, -1, 0, 0, 16384, 0, koopa_npc_Root_Bone_mesh_layer_6),
		GEO_OPEN_NODE(),
			GEO_SWITCH_CASE(2, geo_switch_koopa_col),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, mat_koopa_npc_Koopa),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, mat_koopa_npc_Koopa_RED),
			GEO_CLOSE_NODE(),
			GEO_BONE(LAYER_OPAQUE, 2, 49, 0, 0, 16384, 0, koopa_npc_Torso_mesh_layer_1_tri_0),
			GEO_OPEN_NODE(),
				GEO_BONE(LAYER_OPAQUE, 0, 49, -5, 0, 0, 0, koopa_npc_Head_mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, koopa_npc_Left_Forarm_skinned_mesh_layer_1),
				GEO_BONE(LAYER_OPAQUE, -13, 29, 0, -16384, 16384, 0, koopa_npc_Left_Forarm_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, koopa_npc_Left_Arm_skinned_mesh_layer_1),
					GEO_BONE(LAYER_OPAQUE, 0, 20, 0, 0, 0, 0, koopa_npc_Left_Arm_mesh_layer_1),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, koopa_npc_Left_Leg_skinned_mesh_layer_1),
				GEO_BONE(LAYER_OPAQUE, -14, 0, 8, 0, -10887, -32768, koopa_npc_Left_Leg_mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, koopa_npc_Right_Forarm_skinned_mesh_layer_1),
				GEO_BONE(LAYER_OPAQUE, 13, 29, 0, 0, 0, -16384, koopa_npc_Right_Forarm_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, koopa_npc_Right_Arm_skinned_mesh_layer_1),
					GEO_BONE(LAYER_OPAQUE, 0, 20, 0, 0, 0, 0, koopa_npc_Right_Arm_mesh_layer_1),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, koopa_npc_Right_Leg_skinned_mesh_layer_1),
				GEO_BONE(LAYER_OPAQUE, 14, 0, 8, 0, -10887, -32768, koopa_npc_Right_Leg_mesh_layer_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, koopa_npc_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, koopa_npc_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
