extern const GeoLayout soder_geo[];
extern Lights1 soder_f3dlite_material_001_lights;
extern Lights1 soder_f3dlite_material_lights;
extern u8 soder_soda1_ci4[];
extern u8 soder_soda1_ci4_pal_rgba16[];
extern u8 soder_SODA_i8[];
extern Vtx soder_Cylinder_mesh_layer_1_vtx_cull[8];
extern Vtx soder_Cylinder_mesh_layer_1_vtx_0[326];
extern Gfx soder_Cylinder_mesh_layer_1_tri_0[];
extern Vtx soder_Cylinder_mesh_layer_1_vtx_1[64];
extern Gfx soder_Cylinder_mesh_layer_1_tri_1[];
extern Gfx mat_soder_f3dlite_material_001[];
extern Gfx mat_revert_soder_f3dlite_material_001[];
extern Gfx mat_soder_f3dlite_material[];
extern Gfx soder_Cylinder_mesh_layer_1[];
extern Gfx soder_material_revert_render_settings[];
