extern const GeoLayout buzzy_beetle_Shell[];
extern const GeoLayout buzzy_beetle_geo[];
extern Vtx buzzy_beetle_body_mesh_vtx_0[23];
extern Gfx buzzy_beetle_body_mesh_tri_0[];
extern Vtx buzzy_beetle_body_mesh_vtx_1[28];
extern Gfx buzzy_beetle_body_mesh_tri_1[];
extern Vtx buzzy_beetle_body_mesh_vtx_2[12];
extern Gfx buzzy_beetle_body_mesh_tri_2[];
extern Vtx buzzy_beetle_body_mesh_vtx_3[7];
extern Gfx buzzy_beetle_body_mesh_tri_3[];
extern Vtx buzzy_beetle_head_mesh_vtx_0[41];
extern Gfx buzzy_beetle_head_mesh_tri_0[];
extern Vtx buzzy_beetle_eyes_mesh_vtx_0[8];
extern Gfx buzzy_beetle_eyes_mesh_tri_0[];
extern Vtx buzzy_beetle_legLback_mesh_vtx_0[16];
extern Gfx buzzy_beetle_legLback_mesh_tri_0[];
extern Vtx buzzy_beetle_legLfront_mesh_vtx_0[16];
extern Gfx buzzy_beetle_legLfront_mesh_tri_0[];
extern Vtx buzzy_beetle_legRback_mesh_vtx_0[16];
extern Gfx buzzy_beetle_legRback_mesh_tri_0[];
extern Vtx buzzy_beetle_legRfront_mesh_vtx_0[16];
extern Gfx buzzy_beetle_legRfront_mesh_tri_0[];
extern Vtx buzzy_beetle_Switch_Option_Shell_mesh_vtx_0[23];
extern Gfx buzzy_beetle_Switch_Option_Shell_mesh_tri_0[];
extern Vtx buzzy_beetle_Switch_Option_Shell_mesh_vtx_1[28];
extern Gfx buzzy_beetle_Switch_Option_Shell_mesh_tri_1[];
extern Vtx buzzy_beetle_Switch_Option_Shell_mesh_vtx_2[7];
extern Gfx buzzy_beetle_Switch_Option_Shell_mesh_tri_2[];

extern Gfx buzzy_beetle_body_mesh[];
extern Gfx buzzy_beetle_head_mesh[];
extern Gfx buzzy_beetle_eyes_mesh[];
extern Gfx buzzy_beetle_legLback_mesh[];
extern Gfx buzzy_beetle_legLfront_mesh[];
extern Gfx buzzy_beetle_legRback_mesh[];
extern Gfx buzzy_beetle_legRfront_mesh[];
extern Gfx buzzy_beetle_Switch_Option_Shell_mesh[];
extern Gfx buzzy_beetle_material_revert_render_settings[];

