#include "levels/bob/area_1/geo.inc.c"
#include "levels/bob/area_2/geo.inc.c"
#include "levels/bob/area_3/geo.inc.c"
#include "levels/bob/area_4/geo.inc.c"
#include "levels/bob/area_5/geo.inc.c"
#include "levels/bob/area_6/geo.inc.c"
#include "levels/bob/area_7/geo.inc.c"
