extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern const GeoLayout bob_area_2_geo[];
extern const GeoLayout bob_area_2[];
extern const Collision bob_area_2_collision[];
extern const MacroObject bob_area_2_macro_objs[];
extern const GeoLayout bob_area_3_geo[];
extern const GeoLayout bob_area_3[];
extern const Collision bob_area_3_collision[];
extern const MacroObject bob_area_3_macro_objs[];
extern Lights1 bob_dl_sm64_material_lights;
extern Lights1 bob_dl_f3d_material_lights;
extern Lights1 bob_dl_f3d_material_001_lights;
extern Vtx bob_dl_entrance_mesh_vtx_cull[8];
extern Vtx bob_dl_entrance_mesh_vtx_0[766];
extern Gfx bob_dl_entrance_mesh_tri_0[];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Plane_mesh_layer_1_vtx_0[278];
extern Gfx bob_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Plane_001_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Plane_001_mesh_layer_1_vtx_0[132];
extern Gfx bob_dl_Plane_001_mesh_layer_1_tri_0[];
extern Gfx mat_bob_dl_sm64_material[];
extern Gfx mat_bob_dl_f3d_material[];
extern Gfx mat_bob_dl_f3d_material_001[];
extern Gfx bob_dl_entrance_mesh[];
extern Gfx bob_dl_Plane_mesh_layer_1[];
extern Gfx bob_dl_Plane_001_mesh_layer_1[];
extern Gfx bob_dl_material_revert_render_settings[];
