extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern const GeoLayout bob_area_2_geo[];
extern const GeoLayout bob_area_2[];
extern const Collision bob_area_2_collision[];
extern const MacroObject bob_area_2_macro_objs[];
extern const GeoLayout bob_area_3_geo[];
extern const GeoLayout bob_area_3[];
extern const Collision bob_area_3_collision[];
extern const MacroObject bob_area_3_macro_objs[];
extern const GeoLayout bob_area_4_geo[];
extern const GeoLayout bob_area_4[];
extern const Collision bob_area_4_collision[];
extern const MacroObject bob_area_4_macro_objs[];
extern Lights1 bob_dl_epic_grass_lights;
extern Lights1 bob_dl_side_walk_lights;
extern Lights1 bob_dl_f3d_material_lights;
extern Lights1 bob_dl_stone_epic_lights;
extern Lights1 bob_dl_asphalt_lights;
extern Lights1 bob_dl_fence_lights;
extern Lights1 bob_dl_turner_lights;
extern Lights1 bob_dl_floor_lights;
extern Lights1 bob_dl_floor2_lights;
extern Lights1 bob_dl_f3d_material_001_lights;
extern Lights1 bob_dl_wall_lights;
extern u8 bob_dl_ci4_matt_grass_ci4[];
extern u8 bob_dl_ci4_matt_grass_ci4_pal_rgba16[];
extern u8 bob_dl_ci4_matt_bricks2_ci4[];
extern u8 bob_dl_ci4_matt_bricks2_ci4_pal_rgba16[];
extern u8 bob_dl_ci4_anonmoose_roundbricks1_ci4[];
extern u8 bob_dl_ci4_anonmoose_roundbricks1_ci4_pal_rgba16[];
extern u8 bob_dl_rgba16_anonmoose_asphault1_ci4[];
extern u8 bob_dl_rgba16_anonmoose_asphault1_ci4_pal_rgba16[];
extern u8 bob_dl_ci4_anonmoose_bamboo1_ci4[];
extern u8 bob_dl_ci4_anonmoose_bamboo1_ci4_pal_rgba16[];
extern u8 bob_dl__5_ci8[];
extern u8 bob_dl__5_ci8_pal_rgba16[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_0[14];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_1[14];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Plane_002_mesh_layer_5_vtx_cull[8];
extern Vtx bob_dl_Plane_002_mesh_layer_5_vtx_0[51];
extern Gfx bob_dl_Plane_002_mesh_layer_5_tri_0[];
extern Vtx bob_dl_Plane_002_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Plane_002_mesh_layer_1_vtx_0[8];
extern Gfx bob_dl_Plane_002_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Plane_002_mesh_layer_1_vtx_1[10];
extern Gfx bob_dl_Plane_002_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Plane_002_mesh_layer_1_vtx_2[10];
extern Gfx bob_dl_Plane_002_mesh_layer_1_tri_2[];
extern Vtx bob_dl_Plane_002_mesh_layer_1_vtx_3[38];
extern Gfx bob_dl_Plane_002_mesh_layer_1_tri_3[];
extern Vtx bob_dl_Plane_002_mesh_layer_1_vtx_4[4];
extern Gfx bob_dl_Plane_002_mesh_layer_1_tri_4[];
extern Vtx bob_dl_Plane_002_mesh_layer_1_vtx_5[8];
extern Gfx bob_dl_Plane_002_mesh_layer_1_tri_5[];
extern Vtx bob_dl_turnstile_gate_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_turnstile_gate_mesh_layer_1_vtx_0[216];
extern Gfx bob_dl_turnstile_gate_mesh_layer_1_tri_0[];
extern Vtx bob_dl_floor_meme_mesh_layer_1_vtx_0[1018];
extern Gfx bob_dl_floor_meme_mesh_layer_1_tri_0[];
extern Vtx bob_dl_floor_meme_mesh_layer_1_vtx_1[16];
extern Gfx bob_dl_floor_meme_mesh_layer_1_tri_1[];
extern Vtx bob_dl_floor_meme_mesh_layer_1_vtx_2[32];
extern Gfx bob_dl_floor_meme_mesh_layer_1_tri_2[];
extern Vtx bob_dl_floor_meme_mesh_layer_1_vtx_3[64];
extern Gfx bob_dl_floor_meme_mesh_layer_1_tri_3[];
extern Vtx bob_dl_floor_meme_mesh_layer_5_vtx_0[27];
extern Gfx bob_dl_floor_meme_mesh_layer_5_tri_0[];
extern Vtx bob_dl_floor_meme_mesh_layer_5_vtx_1[16];
extern Gfx bob_dl_floor_meme_mesh_layer_5_tri_1[];
extern Vtx bob_dl_glass_meme_mesh_layer_5_vtx_0[238];
extern Gfx bob_dl_glass_meme_mesh_layer_5_tri_0[];
extern Gfx mat_bob_dl__2639_bottom[];
extern Gfx mat_bob_dl__2639_top[];
extern Gfx mat_bob_dl_window[];
extern Gfx mat_bob_dl_epic_grass[];
extern Gfx mat_revert_bob_dl_epic_grass[];
extern Gfx mat_bob_dl_side_walk[];
extern Gfx mat_revert_bob_dl_side_walk[];
extern Gfx mat_bob_dl_f3d_material[];
extern Gfx mat_bob_dl_stone_epic[];
extern Gfx mat_revert_bob_dl_stone_epic[];
extern Gfx mat_bob_dl_asphalt[];
extern Gfx mat_revert_bob_dl_asphalt[];
extern Gfx mat_bob_dl_fence[];
extern Gfx mat_revert_bob_dl_fence[];
extern Gfx mat_bob_dl_turner[];
extern Gfx mat_revert_bob_dl_turner[];
extern Gfx mat_bob_dl_floor[];
extern Gfx mat_revert_bob_dl_floor[];
extern Gfx mat_bob_dl_floor2[];
extern Gfx mat_revert_bob_dl_floor2[];
extern Gfx mat_bob_dl_window_001[];
extern Gfx mat_revert_bob_dl_window_001[];
extern Gfx mat_bob_dl_f3d_material_001[];
extern Gfx mat_revert_bob_dl_f3d_material_001[];
extern Gfx mat_bob_dl_dirt[];
extern Gfx mat_bob_dl_camera_bounds[];
extern Gfx mat_bob_dl_wall[];
extern Gfx bob_dl_Cube_mesh_layer_1[];
extern Gfx bob_dl_Plane_002_mesh_layer_5[];
extern Gfx bob_dl_Plane_002_mesh_layer_1[];
extern Gfx bob_dl_turnstile_gate_mesh_layer_1[];
extern Gfx bob_dl_floor_meme_mesh_layer_1[];
extern Gfx bob_dl_floor_meme_mesh_layer_5[];
extern Gfx bob_dl_glass_meme_mesh_layer_5[];
extern Gfx bob_dl_material_revert_render_settings[];
