#include "src/game/envfx_snow.h"

const GeoLayout dog_Body_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 81, -12, dog_Chest_mesh_layer_1_mat_override_Body_0),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 19, -8, -35, 0, -90, 180),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_BLeg_L_mesh_layer_1_mat_override_Body_0),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, dog_BKnee_L_skinned_mesh_layer_1_mat_override_Body_0),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 23, 0, dog_BKnee_L_mesh_layer_1_mat_override_Body_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 26, 0, dog_BPaw_L_mesh_layer_1_mat_override_Body_0),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -19, -8, -35, 0, 90, -180),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_BLeg_R_mesh_layer_1_mat_override_Body_0),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, dog_BKnee_R_skinned_mesh_layer_1_mat_override_Body_0),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 23, 0, dog_BKnee_R_mesh_layer_1_mat_override_Body_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 26, 0, dog_BPaw_R_mesh_layer_1_mat_override_Body_0),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_SWITCH_CASE(0, geo_switch_goddard_state),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 29, 65, 45, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_Head_mesh_layer_1_mat_override_Body_0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, dog_Head_mesh_layer_6_mat_override_Body_0),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 24, 32, -39, -40, -1, -127),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_Ear_L_mesh_layer_1_mat_override_Body_0),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -24, 32, -39, -40, 1, 127),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_Ear_R_mesh_layer_1_mat_override_Body_0),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 17, 40, 32, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_Jaw_mesh_layer_1_mat_override_Body_0),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_dog_laser_location_update),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 22, -8, 41, 0, -90, 180),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_FLeg_L_mesh_layer_1_mat_override_Body_0),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, dog_FKnee_L_skinned_mesh_layer_1_mat_override_Body_0),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 23, 0, dog_FKnee_L_mesh_layer_1_mat_override_Body_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 26, 0, dog_FPaw_L_mesh_layer_1_mat_override_Body_0),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -22, -8, 41, 0, 90, -180),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_FLeg_R_mesh_layer_1_mat_override_Body_0),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, dog_FKnee_R_skinned_mesh_layer_1_mat_override_Body_0),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 23, 0, dog_FKnee_R_mesh_layer_1_mat_override_Body_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 26, 0, dog_FPaw_R_mesh_layer_1_mat_override_Body_0),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 24, -35, -87, 0, 0),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_Tail_mesh_layer_1_mat_override_Body_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dog_Body_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 81, -12, dog_Chest_mesh_layer_1_mat_override_Gold_1),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 19, -8, -35, 0, -90, 180),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_BLeg_L_mesh_layer_1_mat_override_Gold_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, dog_BKnee_L_skinned_mesh_layer_1_mat_override_Gold_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 23, 0, dog_BKnee_L_mesh_layer_1_mat_override_Gold_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 26, 0, dog_BPaw_L_mesh_layer_1_mat_override_Gold_1),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -19, -8, -35, 0, 90, -180),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_BLeg_R_mesh_layer_1_mat_override_Gold_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, dog_BKnee_R_skinned_mesh_layer_1_mat_override_Gold_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 23, 0, dog_BKnee_R_mesh_layer_1_mat_override_Gold_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 26, 0, dog_BPaw_R_mesh_layer_1_mat_override_Gold_1),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_SWITCH_CASE(0, geo_switch_goddard_state),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 29, 65, 45, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_Head_mesh_layer_1_mat_override_Gold_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, dog_Head_mesh_layer_6_mat_override_Gold_1),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 24, 32, -39, -40, -1, -127),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_Ear_L_mesh_layer_1_mat_override_Gold_1),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -24, 32, -39, -40, 1, 127),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_Ear_R_mesh_layer_1_mat_override_Gold_1),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 17, 40, 32, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_Jaw_mesh_layer_1_mat_override_Gold_1),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_dog_laser_location_update),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 22, -8, 41, 0, -90, 180),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_FLeg_L_mesh_layer_1_mat_override_Gold_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, dog_FKnee_L_skinned_mesh_layer_1_mat_override_Gold_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 23, 0, dog_FKnee_L_mesh_layer_1_mat_override_Gold_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 26, 0, dog_FPaw_L_mesh_layer_1_mat_override_Gold_1),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -22, -8, 41, 0, 90, -180),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_FLeg_R_mesh_layer_1_mat_override_Gold_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, dog_FKnee_R_skinned_mesh_layer_1_mat_override_Gold_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 23, 0, dog_FKnee_R_mesh_layer_1_mat_override_Gold_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 26, 0, dog_FPaw_R_mesh_layer_1_mat_override_Gold_1),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 24, -35, -87, 0, 0),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_Tail_mesh_layer_1_mat_override_Gold_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dog_Body_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 81, -12, dog_Chest_mesh_layer_1_mat_override_Gold_1),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 19, -8, -35, 0, -90, 180),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_BLeg_L_mesh_layer_1_mat_override_Gold_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, dog_BKnee_L_skinned_mesh_layer_1_mat_override_Gold_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 23, 0, dog_BKnee_L_mesh_layer_1_mat_override_Gold_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 26, 0, dog_BPaw_L_mesh_layer_1_mat_override_Gold_1),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -19, -8, -35, 0, 90, -180),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_BLeg_R_mesh_layer_1_mat_override_Gold_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, dog_BKnee_R_skinned_mesh_layer_1_mat_override_Gold_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 23, 0, dog_BKnee_R_mesh_layer_1_mat_override_Gold_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 26, 0, dog_BPaw_R_mesh_layer_1_mat_override_Gold_1),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_SWITCH_CASE(0, geo_switch_goddard_state),
			GEO_OPEN_NODE(),
				GEO_NODE_START(),
				GEO_OPEN_NODE(),
					GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 29, 65, 45, 0, 0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_Head_mesh_layer_1_mat_override_Gold_1),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, dog_Head_mesh_layer_6_mat_override_Gold_1),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 24, 32, -39, -40, -1, -127),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_Ear_L_mesh_layer_1_mat_override_Gold_1),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -24, 32, -39, -40, 1, 127),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_Ear_R_mesh_layer_1_mat_override_Gold_1),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 17, 40, 32, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_Jaw_mesh_layer_1_mat_override_Gold_1),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_dog_laser_location_update),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 22, -8, 41, 0, -90, 180),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_FLeg_L_mesh_layer_1_mat_override_Gold_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, dog_FKnee_L_skinned_mesh_layer_1_mat_override_Gold_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 23, 0, dog_FKnee_L_mesh_layer_1_mat_override_Gold_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 26, 0, dog_FPaw_L_mesh_layer_1_mat_override_Gold_1),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -22, -8, 41, 0, 90, -180),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_FLeg_R_mesh_layer_1_mat_override_Gold_1),
				GEO_OPEN_NODE(),
					GEO_DISPLAY_LIST(LAYER_OPAQUE, dog_FKnee_R_skinned_mesh_layer_1_mat_override_Gold_1),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 23, 0, dog_FKnee_R_mesh_layer_1_mat_override_Gold_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 26, 0, dog_FPaw_R_mesh_layer_1_mat_override_Gold_1),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
			GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 24, -35, -87, 0, 0),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_Tail_mesh_layer_1_mat_override_Gold_1),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dog_Body_Switch_opt0_Eye_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 29, 65, 45, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_Head_mesh_layer_1_mat_override_Eyes_Closed_2),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, dog_Head_mesh_layer_6_mat_override_Eyes_Closed_2),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 24, 32, -39, -40, -1, -127),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_Ear_L_mesh_layer_1_mat_override_Eyes_Closed_2),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -24, 32, -39, -40, 1, 127),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_Ear_R_mesh_layer_1_mat_override_Eyes_Closed_2),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 17, 40, 32, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_Jaw_mesh_layer_1_mat_override_Eyes_Closed_2),
					GEO_OPEN_NODE(),
						GEO_ASM(0, geo_dog_laser_location_update),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dog_Body_Switch_opt0_Eye_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 29, 65, 45, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_Head_mesh_layer_1_mat_override_Eyes_Open_3),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, dog_Head_mesh_layer_6_mat_override_Eyes_Open_3),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 24, 32, -39, -40, -1, -127),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_Ear_L_mesh_layer_1_mat_override_Eyes_Open_3),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -24, 32, -39, -40, 1, 127),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_Ear_R_mesh_layer_1_mat_override_Eyes_Open_3),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 17, 40, 32, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_Jaw_mesh_layer_1_mat_override_Eyes_Open_3),
					GEO_OPEN_NODE(),
						GEO_ASM(0, geo_dog_laser_location_update),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dog_Body_Switch_opt0_Eye_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 29, 65, 45, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_Head_mesh_layer_1_mat_override_Eyes_Closed_2),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, dog_Head_mesh_layer_6_mat_override_Eyes_Closed_2),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 24, 32, -39, -40, -1, -127),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_Ear_L_mesh_layer_1_mat_override_Eyes_Closed_2),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -24, 32, -39, -40, 1, 127),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_Ear_R_mesh_layer_1_mat_override_Eyes_Closed_2),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 17, 40, 32, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_Jaw_mesh_layer_1_mat_override_Eyes_Closed_2),
					GEO_OPEN_NODE(),
						GEO_ASM(0, geo_dog_laser_location_update),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout dog_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 191, 200),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_SWITCH_CASE(0, geo_switch_goddard_state),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 81, -12, dog_Chest_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 19, -8, -35, 0, -90, 180),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_BLeg_L_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, dog_BKnee_L_skinned_mesh_layer_1),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 23, 0, dog_BKnee_L_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 26, 0, dog_BPaw_L_mesh_layer_1),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -19, -8, -35, 0, 90, -180),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_BLeg_R_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, dog_BKnee_R_skinned_mesh_layer_1),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 23, 0, dog_BKnee_R_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 26, 0, dog_BPaw_R_mesh_layer_1),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_SWITCH_CASE(0, geo_switch_goddard_state),
							GEO_OPEN_NODE(),
								GEO_NODE_START(),
								GEO_OPEN_NODE(),
									GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 29, 65, 45, 0, 0),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_Head_mesh_layer_1),
										GEO_OPEN_NODE(),
											GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, dog_Head_mesh_layer_6),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 24, 32, -39, -40, -1, -127),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_Ear_L_mesh_layer_1),
											GEO_CLOSE_NODE(),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -24, 32, -39, -40, 1, 127),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_Ear_R_mesh_layer_1),
											GEO_CLOSE_NODE(),
											GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 17, 40, 32, 0, 0),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_Jaw_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_dog_laser_location_update),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_BRANCH(1, dog_Body_Switch_opt0_Eye_Switch_opt1),
								GEO_BRANCH(1, dog_Body_Switch_opt0_Eye_Switch_opt2),
								GEO_BRANCH(1, dog_Body_Switch_opt0_Eye_Switch_opt3),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 22, -8, 41, 0, -90, 180),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_FLeg_L_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, dog_FKnee_L_skinned_mesh_layer_1),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 23, 0, dog_FKnee_L_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 26, 0, dog_FPaw_L_mesh_layer_1),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -22, -8, 41, 0, 90, -180),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_FLeg_R_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, dog_FKnee_R_skinned_mesh_layer_1),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 23, 0, dog_FKnee_R_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 26, 0, dog_FPaw_R_mesh_layer_1),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 24, -35, -87, 0, 0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, dog_Tail_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
					GEO_BRANCH(1, dog_Body_Switch_opt1),
					GEO_BRANCH(1, dog_Body_Switch_opt2),
					GEO_BRANCH(1, dog_Body_Switch_opt3),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, dog_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, dog_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
