extern const GeoLayout rovert_fling_geo[];
extern Lights1 rovert_fling_f3d_material_001_lights;
extern u8 rovert_fling_fling_tile_ci4[];
extern u8 rovert_fling_fling_tile_ci4_pal_rgba16[];
extern Vtx rovert_fling_Cube_033_mesh_layer_1_vtx_cull[8];
extern Vtx rovert_fling_Cube_033_mesh_layer_1_vtx_0[20];
extern Gfx rovert_fling_Cube_033_mesh_layer_1_tri_0[];
extern Gfx mat_rovert_fling_f3d_material_001[];
extern Gfx mat_revert_rovert_fling_f3d_material_001[];
extern Gfx rovert_fling_Cube_033_mesh_layer_1[];
extern Gfx rovert_fling_material_revert_render_settings[];
