extern const GeoLayout cozy_pss_bg_geo[];
extern u8 cozy_pss_bg_water_big_chungus_defined_intensity_i4[];
extern u8 cozy_pss_bg_water_pls_try_sharper_intensity_i4[];
extern Vtx cozy_pss_bg_AABG3D_mesh_layer_0_vtx_cull[8];
extern Vtx cozy_pss_bg_AABG3D_mesh_layer_0_vtx_0[118];
extern Gfx cozy_pss_bg_AABG3D_mesh_layer_0_tri_0[];
extern Gfx mat_cozy_pss_bg_cozyskybox_layer0[];
extern Gfx mat_revert_cozy_pss_bg_cozyskybox_layer0[];
extern Gfx cozy_pss_bg_AABG3D_mesh_layer_0[];
extern Gfx cozy_pss_bg_material_revert_render_settings[];
