extern const GeoLayout couch_geo[];
extern Lights1 couch_the_wood_lights;
extern Lights1 couch_the_couches_layer1_lights;
extern u8 couch_ci4_nat_wood1_ci4[];
extern u8 couch_ci4_nat_wood1_ci4_pal_rgba16[];
extern u8 couch_ci4_nat_wall_ci4[];
extern u8 couch_ci4_nat_wall_ci4_pal_rgba16[];
extern Vtx couch_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx couch_Cube_mesh_layer_1_vtx_0[146];
extern Gfx couch_Cube_mesh_layer_1_tri_0[];
extern Vtx couch_Cube_mesh_layer_1_vtx_1[50];
extern Gfx couch_Cube_mesh_layer_1_tri_1[];
extern Gfx mat_couch_the_wood[];
extern Gfx mat_revert_couch_the_wood[];
extern Gfx mat_couch_the_couches_layer1[];
extern Gfx mat_revert_couch_the_couches_layer1[];
extern Gfx couch_Cube_mesh_layer_1[];
extern Gfx couch_material_revert_render_settings[];
