#include "src/game/envfx_snow.h"

const GeoLayout water_top_geo[] = {
	GEO_CULLING_RADIUS(10000),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ASM(LAYER_TRANSPARENT, geo_set_water_lights),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 5700, 0, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_ASM(5, move_water_top),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, water_top_zoutside_skinned_mesh_layer_5),
				GEO_ANIMATED_PART(LAYER_TRANSPARENT, -100, 0, 0, water_top_zoutside_mesh_layer_5),
				GEO_OPEN_NODE(),
					GEO_ASM(4, move_water_top),
					GEO_DISPLAY_LIST(LAYER_TRANSPARENT, water_top_ring_4_skinned_mesh_layer_5),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, -1100, 0, 0, water_top_ring_4_mesh_layer_5),
					GEO_OPEN_NODE(),
						GEO_ASM(3, move_water_top),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, water_top_ring_3_skinned_mesh_layer_5),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, -1100, 0, 0, water_top_ring_3_mesh_layer_5),
						GEO_OPEN_NODE(),
							GEO_ASM(2, move_water_top),
							GEO_DISPLAY_LIST(LAYER_TRANSPARENT, water_top_ring_2_skinned_mesh_layer_5),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, -1100, 0, 0, water_top_ring_2_mesh_layer_5),
							GEO_OPEN_NODE(),
								GEO_ASM(1, move_water_top),
								GEO_DISPLAY_LIST(LAYER_TRANSPARENT, water_top_ring_1_skinned_mesh_layer_5),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, -1200, 0, 0, water_top_ring_1_mesh_layer_5),
								GEO_OPEN_NODE(),
									GEO_ASM(0, move_water_top),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, water_top_center_skinned_mesh_layer_5),
									GEO_ANIMATED_PART(LAYER_TRANSPARENT, -1100, 0, 0, water_top_center_mesh_layer_5),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, water_top_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
