#include "src/game/envfx_snow.h"

const GeoLayout ddd_area_2_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 0, 6000, 0),
		GEO_OPEN_NODE(),
			GEO_ASM(LAYER_OPAQUE, geo_set_global_fog),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_CentralArea_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ddd_dl_CentralArea_mesh_layer_5),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, 1862, 1825, -2563, ddd_dl_ObservingGlass_mesh_layer_5),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE_INTER, 0, 6000, 0, ddd_dl_TubeToArea3_mesh_layer_3),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 0, 6000, 0, ddd_dl_TunnelBetween_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout ddd_area_2[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, -10000, 0, 0, -10100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, ddd_area_2_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_SNOW_WATER, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_INTER, ddd_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ddd_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
