#include "src/game/envfx_snow.h"

const GeoLayout ddd_area_2_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(12, geo_switch_area),
		GEO_OPEN_NODE(),
			GEO_BRANCH(1, ddd_dl_Room1_geo),
			GEO_BRANCH(1, ddd_dl_Room2_geo),
			GEO_BRANCH(1, ddd_dl_Room3_geo),
			GEO_BRANCH(1, ddd_dl_Room4_geo),
			GEO_BRANCH(1, ddd_dl_Room5_Switch_Across_Gap_geo),
			GEO_BRANCH(1, ddd_dl_Room6_geo),
			GEO_BRANCH(1, ddd_dl_Room7_PostPurpTransitional_geo),
			GEO_BRANCH(1, ddd_dl_Room8_SemiCircle_geo),
			GEO_BRANCH(1, ddd_dl_Room9_to_the_whirlpool_geo),
			GEO_BRANCH(1, ddd_dl_ZRoom10_whirlpool_geo),
			GEO_BRANCH(1, ddd_dl_ZZRoom11_doge_room_geo),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout ddd_dl_Room1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_CentralArea_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ddd_dl_CentralArea_mesh_layer_5),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 600, 1000, 0, ddd_dl_FlipperLightsGeo_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 600, 200, 0, ddd_dl_FlipperLightsGeo_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_FlipperLightsGeo_001_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -3700, -3300, -4900, 0, -90, 0, ddd_dl_FlipperLightsGeo_003_mesh_layer_1),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -3900, -3500, -4700, 0, 180, 0, ddd_dl_FlipperLightsGeo_004_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_MainArea_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, ddd_dl_MainArea_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ddd_dl_ObservingGlass_mesh_layer_5),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE_INTER, -574, -4000, -3129, 0, -45, 0, ddd_dl_TubeToArea3_mesh_layer_3),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, 0, 6000, 0, ddd_dl_TunnelBetween_005_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_MainAreaConnectOut_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout ddd_dl_Room2_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_MainAreaConnectOut_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_SecretRoomDontTell_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, ddd_dl_SecretRoomDontTell_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_MainArea_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, ddd_dl_MainArea_mesh_layer_4),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, -3100, -5150, -1300, ddd_dl_glasso_tubo_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ddd_dl_ObservingGlass_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout ddd_dl_Room3_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, -3100, -5150, -1300, ddd_dl_glasso_tubo_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_SecretRoomDontTell_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, ddd_dl_SecretRoomDontTell_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_MainAreaConnectOut_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_SuperSecretTunnelToSecretRoom_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_AboveTheTube_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout ddd_dl_Room4_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_AboveTheTube_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_INTER, ddd_dl_AboveTheTube_001_mesh_layer_7),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, -3100, -5150, -1300, ddd_dl_glasso_tubo_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_AcrossTheGap_mesh_layer_1),
		GEO_ASM(0, geo_backdrop_move_cozies),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE_INTER, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ASM((0x0A << 8) | LAYER_OPAQUE_INTER, geo_mountain_fog),
			GEO_DISPLAY_LIST(LAYER_OPAQUE_INTER, ddd_dl_A_Front_Mountains_mesh_layer_3),
			GEO_ASM((0x30 << 8) | LAYER_OPAQUE_INTER, geo_mountain_fog),
			GEO_DISPLAY_LIST(LAYER_OPAQUE_INTER, ddd_dl_A_ZABack_Mountains_001_mesh_layer_3),
			GEO_ASM((0x30 << 8) | LAYER_OPAQUE_INTER, geo_mountain_fog),
			GEO_DISPLAY_LIST(LAYER_OPAQUE_INTER, ddd_dl_A_ZBack_Mountains_mesh_layer_3),
			GEO_DISPLAY_LIST(LAYER_OPAQUE_INTER, ddd_dl_ZZSkyOcean_mesh_layer_3),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout ddd_dl_Room5_Switch_Across_Gap_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_AcrossTheGap_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_AcrossTheGap_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_SuperSecretTunnelToSecretRoom_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_AboveTheTube_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_TransitiontoPostPurpTransitional_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_PostPurpTransitional_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, ddd_dl_PostPurpTransitional_mesh_layer_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout ddd_dl_Room6_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_SuperSecretTunnelToSecretRoom_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_AcrossTheGap_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_SecretRoomDontTell_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, ddd_dl_SecretRoomDontTell_mesh_layer_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout ddd_dl_Room7_PostPurpTransitional_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_PostPurpTransitional_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, ddd_dl_PostPurpTransitional_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_TransitiontoPostPurpTransitional_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_TubeLights_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_AcrossTheGap_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout ddd_dl_Room8_SemiCircle_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_A1_SemiCircleTube_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, ddd_dl_A1_SemiCircleTube_mesh_layer_4),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, 7670, 1500, -5720, ddd_dl_CloudInTheHolePath_001_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_ZSemiCircleRoom_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_ZSemiCircleRoom_purpfloor_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_ZSemiCircleRoom_purpwall_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_ZSemiCircleRoom_toob_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_ZSemiCircleRoom_towhirlpool_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_PostPurpTransitional_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, ddd_dl_PostPurpTransitional_mesh_layer_4),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_TubeLights_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_tothewhirlpoolmesh_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout ddd_dl_Room9_to_the_whirlpool_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_tothewhirlpoolmesh_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_tothewhirlpoolmesh_tinysteppies_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_ZSemiCircleRoom_towhirlpool_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_tothewhirlpoolmesh_butwhirlpoolroom_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout ddd_dl_ZRoom10_whirlpool_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_FORCE, ddd_dl_A_ATubeToDaTOP_mesh_layer_0),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, 1, 0, 0, ddd_dl_Cylinder_001_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_tothewhirlpoolmesh_butwhirlpoolroom_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ddd_dl_tothewhirlpoolmesh_butwhirlpoolroom_001_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ddd_dl_tothewhirlpoolmesh_butwhirlpoolroom_002_mesh_layer_5),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT_INTER, 1, 6000, 0, ddd_dl_TunnelBetween_001_mesh_layer_7),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, 1, 6000, 0, ddd_dl_TunnelBetween_002_mesh_layer_5),
		GEO_ASM(LAYER_TRANSPARENT_INTER, geo_set_global_fog),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 1, 10000, 0),
		GEO_ASM(LAYER_TRANSPARENT, geo_set_global_fog),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 1, 10000, 0),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_Zwhirlpoolroom_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 1, 6000, 0, ddd_dl_TunnelBetween_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_ZZZZZZZZZZZZZwhirlpoolroom_001_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_tothewhirlpoolmesh_tinysteppies_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_whirlpoolroom_004_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout ddd_dl_ZZRoom11_doge_room_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_TRANSPARENT, 0, 0, 600, ddd_dl_whirlpoolroom_001_mesh_layer_5),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_whirlpoolroom_002_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_whirlpoolroom_004_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_ZZZZZZZZZZZZZwhirlpoolroom_001_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout ddd_area_2[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, -10000, 0, 0, -10100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, ddd_area_2_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_SNOW_WATER, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_FORCE, ddd_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_INTER, ddd_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, ddd_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, ddd_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_INTER, ddd_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
