#include "src/game/envfx_snow.h"

const GeoLayout bbh_area_2_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(3, geo_switch_area),
		GEO_OPEN_NODE(),
			GEO_BRANCH(1, bbh_dl_21__RedCoins_geo),
			GEO_BRANCH(1, bbh_dl_22__Fwoosh_geo),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bbh_dl_21__RedCoins_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -4247, -152, -4070, 0, 7, 0),
		GEO_OPEN_NODE(),
			GEO_ASM(1, geo_comit_cpu_fog),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_BigCloud_001_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -8373, -914, 3447, 0, 7, 0),
		GEO_OPEN_NODE(),
			GEO_ASM(1, geo_comit_cpu_fog),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_BigCloud_002_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -7085, -512, -624, 0, 7, 0),
		GEO_OPEN_NODE(),
			GEO_ASM(1, geo_comit_cpu_fog),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_BigCloud_006_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -2828, -322, 5399, 0, 87, 0),
		GEO_OPEN_NODE(),
			GEO_ASM(1, geo_comit_cpu_fog),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_GenericCloudPlat_002_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 5930, 72, 4641, 0, 87, 0),
		GEO_OPEN_NODE(),
			GEO_ASM(1, geo_comit_cpu_fog),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_GenericCloudPlat_004_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 9678, 1102, 6696, 0, 87, 0),
		GEO_OPEN_NODE(),
			GEO_ASM(1, geo_comit_cpu_fog),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_GenericCloudPlat_005_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 12800, 48, 4834, 0, 87, 0),
		GEO_OPEN_NODE(),
			GEO_ASM(1, geo_comit_cpu_fog),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_GenericCloudPlat_006_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 7617, 219, 9972, 0, 87, 0),
		GEO_OPEN_NODE(),
			GEO_ASM(1, geo_comit_cpu_fog),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_GenericCloudPlat_007_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -11841, -905, 3911, 0, -156, 0),
		GEO_OPEN_NODE(),
			GEO_ASM(1, geo_comit_cpu_fog),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Inside_002_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -5423, -76, -6798, 0, -156, 0),
		GEO_OPEN_NODE(),
			GEO_ASM(1, geo_comit_cpu_fog),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Inside_004_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -5431, -50, 2568, 0, -156, 0, bbh_dl_Inside_006_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bbh_dl_22__Fwoosh_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, 15015, 10045, -12251, 0, -156, 0, bbh_dl_FwooshRoom_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bbh_dl_FwooshRoom_mesh_layer_5),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 14552, 8125, -12461, bbh_dl_Magnet_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bbh_area_2[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0x0001),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 65534, 0, 0, 65534, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, bbh_area_2_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bbh_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
