#include "src/game/envfx_snow.h"

const GeoLayout bbh_area_2_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(3, geo_switch_area),
		GEO_OPEN_NODE(),
			GEO_BRANCH(1, bbh_dl_21__RedCoins_geo),
			GEO_BRANCH(1, bbh_dl_22__Fwoosh_geo),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bbh_dl_21__RedCoins_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ASM(1, geo_comit_cpu_fog),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_BigCloud_001_mesh_layer_1),
		GEO_ASM(1, geo_comit_cpu_fog),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_BigCloud_002_mesh_layer_1),
		GEO_ASM(1, geo_comit_cpu_fog),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_BigCloud_006_mesh_layer_1),
		GEO_ASM(1, geo_comit_cpu_fog),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_GenericCloudPlat_002_mesh_layer_1),
		GEO_ASM(1, geo_comit_cpu_fog),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_GenericCloudPlat_004_mesh_layer_1),
		GEO_ASM(1, geo_comit_cpu_fog),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_GenericCloudPlat_005_mesh_layer_1),
		GEO_ASM(1, geo_comit_cpu_fog),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_GenericCloudPlat_006_mesh_layer_1),
		GEO_ASM(1, geo_comit_cpu_fog),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_GenericCloudPlat_007_mesh_layer_1),
		GEO_ASM(1, geo_comit_cpu_fog),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Inside_002_mesh_layer_1),
		GEO_ASM(1, geo_comit_cpu_fog),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Inside_004_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_Inside_006_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bbh_dl_22__Fwoosh_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_FwooshRoom_mesh_layer_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bbh_dl_FwooshRoom_mesh_layer_5),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, -65534, 0, 0, bbh_dl_Magnet_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bbh_area_2[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0x0001),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 65534, 0, 0, 65534, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, bbh_area_2_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bbh_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, bbh_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
