#include "src/game/envfx_snow.h"

const GeoLayout bits_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(4, geo_switch_area),
		GEO_OPEN_NODE(),
			GEO_BRANCH(1, bits_dl_11__room_geo),
			GEO_BRANCH(1, bits_dl_11__room_002_geo),
			GEO_BRANCH(1, bits_dl_13__room_001_geo),
		GEO_CLOSE_NODE(),
		GEO_ROTATION_NODE(LAYER_OPAQUE, 0, 90, 0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bits_dl_11__room_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ROTATION_NODE(LAYER_OPAQUE, 0, 90, 0),
		GEO_OPEN_NODE(),
			GEO_ROTATION_NODE_WITH_DL(LAYER_OPAQUE, 0, -90, 0, bits_dl_BigCloud2Console_001_mesh_layer_1),
			GEO_ROTATION_NODE_WITH_DL(LAYER_OPAQUE, 0, -90, 0, bits_dl_CloudIsland3_003_mesh_layer_1),
			GEO_ROTATION_NODE_WITH_DL(LAYER_ALPHA, 0, -90, 0, bits_dl_Flower_006_mesh_layer_4),
			GEO_ROTATION_NODE_WITH_DL(LAYER_OPAQUE, 0, -90, 0, bits_dl_GenericCloudPlats3_004_mesh_layer_1),
			GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -13215, 3690, -4773, 0, -90, 0, bits_dl_Scaffolding_001_mesh_layer_1),
			GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -13915, 290, 4883, 0, -90, 0, bits_dl_Shack_003_mesh_layer_1),
			GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -6709, 1571, 4670, -10, 73, 97, bits_dl_Shell3_001_mesh_layer_1),
			GEO_TRANSLATE_ROTATE_WITH_DL(LAYER_OPAQUE, -8498, 219, -1804, 0, -170, 0, bits_dl_Sign3_001_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, bits_dl_Sign3_001_mesh_layer_6),
			GEO_CLOSE_NODE(),
			GEO_ROTATION_NODE_WITH_DL(LAYER_OPAQUE, 0, -90, 0, bits_dl_ZBuilding_002_mesh_layer_1),
			GEO_ROTATION_NODE_WITH_DL(LAYER_OPAQUE, 0, -90, 0, bits_dl_ZBuilding_007_mesh_layer_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bits_dl_11__room_002_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ROTATION_NODE(LAYER_OPAQUE, 0, 90, 0),
		GEO_OPEN_NODE(),
			GEO_ROTATION_NODE_WITH_DL(LAYER_OPAQUE, 0, -90, 0, bits_dl_CloudIsland3_004_mesh_layer_1),
			GEO_ROTATION_NODE_WITH_DL(LAYER_OPAQUE, 0, -90, 0, bits_dl_GenericCloudPlat_009_mesh_layer_1),
			GEO_ROTATION_NODE_WITH_DL(LAYER_OPAQUE, 0, -90, 0, bits_dl_Inside_001_mesh_layer_1),
			GEO_ROTATION_NODE_WITH_DL(LAYER_OPAQUE, 0, -90, 0, bits_dl_Inside_005_mesh_layer_1),
			GEO_ROTATION_NODE_WITH_DL(LAYER_OPAQUE, 0, -90, 0, bits_dl_ZBuilding_005_mesh_layer_1),
			GEO_ROTATION_NODE_WITH_DL(LAYER_OPAQUE, 0, -90, 0, bits_dl_ZBuilding_006_mesh_layer_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bits_dl_13__room_001_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ROTATION_NODE(LAYER_OPAQUE, 0, 90, 0),
		GEO_OPEN_NODE(),
			GEO_ROTATION_NODE_WITH_DL(LAYER_OPAQUE, 0, -90, 0, bits_dl_BigCloud3Col_002_mesh_layer_1),
			GEO_ROTATION_NODE_WITH_DL(LAYER_OPAQUE, 90, 0, 90, bits_dl_CenterPlat_008_mesh_layer_1),
			GEO_ROTATION_NODE_WITH_DL(LAYER_OPAQUE, 0, -90, 0, bits_dl_GenericCloudPlats3_005_mesh_layer_1),
			GEO_ROTATION_NODE_WITH_DL(LAYER_FORCE, 90, 0, 90, bits_dl_Skybox_mesh_layer_0),
			GEO_ROTATION_NODE_WITH_DL(LAYER_OPAQUE, 0, -90, 0, bits_dl_ZBuilding_003_mesh_layer_1),
			GEO_ROTATION_NODE_WITH_DL(LAYER_OPAQUE, 0, -90, 0, bits_dl_ZBuilding_004_mesh_layer_1),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bits_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_PURPLE_SKY, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, bits_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_FORCE, bits_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, bits_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, bits_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, bits_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
