extern const GeoLayout cheeze_bombwall2_geo[];
extern Lights1 cheeze_bombwall2_fortress_003_lights;
extern Lights1 cheeze_bombwall2_crack_lights;
extern u8 cheeze_bombwall2_xx_9_ci8[];
extern u8 cheeze_bombwall2_xx_9_ci8_pal_rgba16[];
extern u8 cheeze_bombwall2_crack_ia8[];
extern Vtx cheeze_bombwall2_opa_001_mesh_layer_1_vtx_cull[8];
extern Vtx cheeze_bombwall2_opa_001_mesh_layer_1_vtx_0[4];
extern Gfx cheeze_bombwall2_opa_001_mesh_layer_1_tri_0[];
extern Vtx cheeze_bombwall2_opa_001_mesh_layer_6_vtx_cull[8];
extern Vtx cheeze_bombwall2_opa_001_mesh_layer_6_vtx_0[4];
extern Gfx cheeze_bombwall2_opa_001_mesh_layer_6_tri_0[];
extern Gfx mat_cheeze_bombwall2_fortress_003[];
extern Gfx mat_revert_cheeze_bombwall2_fortress_003[];
extern Gfx mat_cheeze_bombwall2_crack[];
extern Gfx cheeze_bombwall2_opa_001_mesh_layer_1[];
extern Gfx cheeze_bombwall2_opa_001_mesh_layer_6[];
extern Gfx cheeze_bombwall2_material_revert_render_settings[];
