extern const GeoLayout cheeze_bombwall2_geo[];
extern Lights1 cheeze_bombwall2_fortress_001_lights;
extern Lights1 cheeze_bombwall2_crack_lights;
extern u8 cheeze_bombwall2_Bctrwi3_wall2_comp_i4[];
extern u8 cheeze_bombwall2_crack_ia8[];
extern Vtx cheeze_bombwall2_bomb2_mesh_layer_1_vtx_cull[8];
extern Vtx cheeze_bombwall2_bomb2_mesh_layer_1_vtx_0[4];
extern Gfx cheeze_bombwall2_bomb2_mesh_layer_1_tri_0[];
extern Vtx cheeze_bombwall2_bomb2_mesh_layer_6_vtx_cull[8];
extern Vtx cheeze_bombwall2_bomb2_mesh_layer_6_vtx_0[4];
extern Gfx cheeze_bombwall2_bomb2_mesh_layer_6_tri_0[];
extern Gfx mat_cheeze_bombwall2_fortress_001[];
extern Gfx mat_cheeze_bombwall2_crack[];
extern Gfx cheeze_bombwall2_bomb2_mesh_layer_1[];
extern Gfx cheeze_bombwall2_bomb2_mesh_layer_6[];
extern Gfx cheeze_bombwall2_material_revert_render_settings[];
