extern const GeoLayout turnstile_geo[];
extern Lights1 turnstile_tsile_lights;
extern Vtx turnstile_TurnStile_mesh_layer_1_vtx_cull[8];
extern Vtx turnstile_TurnStile_mesh_layer_1_vtx_0[200];
extern Gfx turnstile_TurnStile_mesh_layer_1_tri_0[];
extern Vtx turnstile_TurnStile_mesh_layer_5_vtx_cull[8];
extern Vtx turnstile_TurnStile_mesh_layer_5_vtx_0[32];
extern Gfx turnstile_TurnStile_mesh_layer_5_tri_0[];
extern Gfx mat_turnstile_tsile[];
extern Gfx mat_revert_turnstile_tsile[];
extern Gfx mat_turnstile_another_wndo[];
extern Gfx turnstile_TurnStile_mesh_layer_1[];
extern Gfx turnstile_TurnStile_mesh_layer_5[];
extern Gfx turnstile_material_revert_render_settings[];
