extern const GeoLayout fade_cloud_switch_opt1_switch2_opt1[];
extern const GeoLayout fade_cloud_switch_opt1_switch2_opt2[];
extern const GeoLayout fade_cloud_switch_opt1[];
extern const GeoLayout fade_cloud_switch_opt0_switch2_opt1[];
extern const GeoLayout fade_cloud_switch_opt0_switch2_opt2[];
extern const GeoLayout fade_cloud_geo[];
extern Lights1 fade_cloud_Cloud_004_lights;
extern Lights1 fade_cloud_CloudGold_lights;
extern Lights1 fade_cloud_CloudBlue_lights;
extern u8 fade_cloud_clouds_i8_i8[];
extern u8 fade_cloud_clouds_i8_i8_copy[];
extern u8 fade_cloud_clouds_i8_i8_copy_copy[];
extern Vtx fade_cloud_dl5_mesh_layer_1_vtx_0[29];
extern Gfx fade_cloud_dl5_mesh_layer_1_tri_0[];
extern Gfx mat_fade_cloud_Cloud_004[];
extern Gfx mat_fade_cloud_CloudGold[];
extern Gfx mat_fade_cloud_CloudBlue[];
extern Gfx fade_cloud_dl5_mesh_layer_1[];
extern Gfx fade_cloud_dl5_mesh_layer_1_mat_override_CloudGold_0[];
extern Gfx fade_cloud_dl5_mesh_layer_1_mat_override_CloudBlue_1[];
extern Gfx fade_cloud_material_revert_render_settings[];
