extern const GeoLayout cherry_tree_geo[];
extern Lights1 cherry_tree_f3dlite_material_003_lights;
extern Lights1 cherry_tree_f3dlite_material_002_lights;
extern u8 cherry_tree_cherrywood_ci8[];
extern u8 cherry_tree_cherrywood_ci8_pal_rgba16[];
extern u8 cherry_tree_imgonline_com_ua_TextureSeamless_U6VGIrMYdvr_ci4[];
extern u8 cherry_tree_imgonline_com_ua_TextureSeamless_U6VGIrMYdvr_ci4_pal_rgba16[];
extern Vtx cherry_tree_Circle_mesh_layer_1_vtx_cull[8];
extern Vtx cherry_tree_Circle_mesh_layer_1_vtx_0[114];
extern Gfx cherry_tree_Circle_mesh_layer_1_tri_0[];
extern Vtx cherry_tree_Circle_mesh_layer_1_vtx_1[132];
extern Gfx cherry_tree_Circle_mesh_layer_1_tri_1[];
extern Gfx mat_cherry_tree_f3dlite_material_003[];
extern Gfx mat_revert_cherry_tree_f3dlite_material_003[];
extern Gfx mat_cherry_tree_f3dlite_material_002[];
extern Gfx mat_revert_cherry_tree_f3dlite_material_002[];
extern Gfx cherry_tree_Circle_mesh_layer_1[];
extern Gfx cherry_tree_material_revert_render_settings[];
