extern const GeoLayout cherry_tree_geo[];
extern u8 cherry_tree_EARTHWORM_JIM_3D_28CD13B7_0_2_all_ci4[];
extern u8 cherry_tree_EARTHWORM_JIM_3D_28CD13B7_0_2_all_ci4_pal_rgba16[];
extern u8 cherry_tree_pinkTreeLeaves_ci8[];
extern u8 cherry_tree_pinkTreeLeaves_ci8_pal_rgba16[];
extern Vtx cherry_tree_Cherry_Tree_mesh_layer_1_vtx_0[148];
extern Gfx cherry_tree_Cherry_Tree_mesh_layer_1_tri_0[];
extern Vtx cherry_tree_Cherry_Tree_mesh_layer_1_vtx_1[128];
extern Gfx cherry_tree_Cherry_Tree_mesh_layer_1_tri_1[];
extern Gfx mat_cherry_tree_tree_bark[];
extern Gfx mat_revert_cherry_tree_tree_bark[];
extern Gfx mat_cherry_tree_vleaves_002[];
extern Gfx mat_revert_cherry_tree_vleaves_002[];
extern Gfx cherry_tree_Cherry_Tree_mesh_layer_1[];
extern Gfx cherry_tree_material_revert_render_settings[];
