extern const GeoLayout rain_cloud_switch_opt1[];
extern const GeoLayout rain_cloud_geo[];
extern Lights1 rain_cloud_CryCloud_lights;
extern Lights1 rain_cloud_CryEyes2_lights;
extern Lights1 rain_cloud_CryEyes_lights;
extern Lights1 rain_cloud_CryEyes3_lights;
extern u8 rain_cloud_clouds_i8_i8[];
extern u8 rain_cloud_tears_rgba32[];
extern u8 rain_cloud_notcrying_1_ia16[];
extern u8 rain_cloud_notcrying_2_ia16[];
extern Vtx rain_cloud_rainbody_mesh_layer_1_vtx_0[29];
extern Gfx rain_cloud_rainbody_mesh_layer_1_tri_0[];
extern Vtx rain_cloud_raintear_mesh_layer_5_vtx_0[4];
extern Gfx rain_cloud_raintear_mesh_layer_5_tri_0[];
extern Vtx rain_cloud_rainface_mesh_layer_5_vtx_0[4];
extern Gfx rain_cloud_rainface_mesh_layer_5_tri_0[];
extern Gfx mat_rain_cloud_CryCloud[];
extern Gfx mat_rain_cloud_CryEyes2[];
extern Gfx mat_rain_cloud_CryEyes[];
extern Gfx mat_rain_cloud_CryEyes3[];
extern Gfx rain_cloud_rainbody_mesh_layer_1[];
extern Gfx rain_cloud_raintear_mesh_layer_5[];
extern Gfx rain_cloud_rainface_mesh_layer_5[];
extern Gfx rain_cloud_rainface_mesh_layer_5_mat_override_CryEyes3_0[];
extern Gfx rain_cloud_material_revert_render_settings[];
