COURSE_ACTS(COURSE_BOB, " 3 HYPNOTIZING HIGH RISE",
       "ARE DOGS EVEN ALLOWED IN THIS ESTABLISHMENT?", \
       "FLOOR 2: HELP PRINCESS PEACH MOVE IN", \
       "PARTY ON FLOOR 3", \
       "FLOOR 4 IS FLOODED", \
       "SOMETHING BALCONY", \
       "HELP LUIGI MOVE OUT" \
)

COURSE_ACTS(COURSE_WF, " 4 KOOPA ATOLL",
       "X MARKS THE SPOT"        , "WATER RACE WITH KOOPA THE QUICK"    , "RESTLESS VILLAIN IN THE VOLCANO",
       "RACE UP THE ROCK FACE", "RED COINS IN THE CORAL REEF"    , "IN THE SEAGULL'S SHIP IN THE BOTTLE")

COURSE_ACTS(COURSE_JRB, " 6 SWIRLING CIRCUS",
       "CAROUSEL CLIMB"    , "FRIGHTENING FERRIS WHEEL" , "RED COINS AT WHILRIGIG WAYPOINTS",
       "TRAPEZE TUMBLE"  , "CENTER STAGE SHOWDOWN"     , "CLOSING THE CIRCUS")

COURSE_ACTS(COURSE_CCM, " 5 PEACH RUINS",
       "ACROSS THE FRAGILE BRIDGE", "TOWER RAFT RIDE", "HIDDEN AMONG THE ASHES",
       "8 RED HOT REDS"  , "FREE THE ENSLAVED TOADS"   , "GENERAL MOTOS")

COURSE_ACTS(COURSE_BBH, " 2 CUMULUS CORRECTIONAL CENTER",
       "TAKING THE TOUR"               , "LOST IN THE CLOUDS"            , "RED COINS IN THE FACILITY",
       "RAINBOW RIDE TO THE TOWER"     , "THE THUNDEROUS TROUBLEMAKERS"  , "THE CUMULUS BREATH CONTROL COURSE")

COURSE_ACTS(COURSE_HMC, " 9 FORBIDDEN FACTORY",
       "TURN ON THE GENERATOR"  , "UNLOCK THE MAINTENANCE ROOM"       , "RED COINS WITH FREE SHIPPING",
       "PRODUCTION LINE RUSH"     , "RED BLOCK ROUNDUP"     , "KING GOOPA BENEATH THE SCENES")

COURSE_ACTS(COURSE_LLL, " 8 SAKURA STRONGHOLD",
       "TO THE FOREST'S SHRINE"            , "TOP OF THE FORTRESS"             , "SECRET COINS IN TOWN",
       "COURTYARD'S 8 RED COINS"           , "SECRET ENTERANCE FROM THE LAKE"  , "UPSTAIRS OF THE DUNGEON")

COURSE_ACTS(COURSE_SSL, " 7 AWE-INSPIRING SPIRES",
       "HIGH ON THE AZURE TOWER"       , "FROSTED TIPS"                  , "WALL-KICKING DIVES",
       "SECRETS IN THE SILVER TOWER"   , "THE INVISIBLE PATH"            , "RED TOWER'S 8 COINS")

COURSE_ACTS(COURSE_DDD, "10 BOWSER'S SCUBA TOWER",
       "THE LAB DRAIN"                 , "THE SIDE ENTRANCE"             , "THE PIT",
       "THE OVERHANG"                  , "THE WHIRLPOOL"                 , "THE COINS IN THE CLOUDS")

COURSE_ACTS(COURSE_SL, " 6 UPTURNED DEEPS",
       "THE ELDER'S REQUEST"            , "CHILL WITH THE BULLY"          , "IN THE DEEP FREEZE",
       "WHIRL FROM THE FREEZING POND"  , "SHELL SHREDDIN' FOR RED COINS" , "INTO THE IGLOO")

COURSE_ACTS(COURSE_WDW, " 1 MAPLE MARKINDON",
       "SHOCKING ARROW LIFTS!"         , "TOP O' THE TOWN"               , "SECRETS IN THE SHALLOWS & SKY",
       "EXPRESS ELEVATOR--HURRY UP!"   , "GO TO TOWN FOR RED COINS"      , "QUICK RACE THROUGH DOWNTOWN!")

COURSE_ACTS(COURSE_TTM, "12 TALL, TALL MOUNTAIN",
       "SCALE THE MOUNTAIN"            , "MYSTERY OF THE MONKEY CAGE"    , "SCARY 'SHROOMS, RED COINS",
       "MYSTERIOUS MOUNTAINSIDE"       , "BREATHTAKING VIEW FROM BRIDGE" , "BLAST TO THE LONELY MUSHROOM")

COURSE_ACTS(COURSE_THI, "13 TINY-HUGE ISLAND",
       "PLUCK THE PIRANHA FLOWER"      , "THE TIP TOP OF THE HUGE ISLAND", "REMATCH WITH KOOPA THE QUICK",
       "FIVE ITTY BITTY SECRETS"       , "WIGGLER'S RED COINS"           , "MAKE WIGGLER SQUIRM")

COURSE_ACTS(COURSE_TTC, "14 TICK TOCK CLOCK",
       "ROLL INTO THE CAGE"            , "THE PIT AND THE PENDULUMS"     , "GET A HAND",
       "STOMP ON THE THWOMP"           , "TIMED JUMPS ON MOVING BARS"    , "STOP TIME FOR RED COINS")

COURSE_ACTS(COURSE_RR, "15 RAINBOW RIDE",
       "CRUISER CROSSING THE RAINBOW"  , "THE BIG HOUSE IN THE SKY"      , "COINS AMASSED IN A MAZE",
       "SWINGIN' IN THE BREEZE"        , "TRICKY TRIANGLES!"             , "SOMEWHERE OVER THE RAINBOW")

SECRET_STAR(COURSE_BITDW, "   BOWSER'S RAINBOW RINGS")
SECRET_STAR(COURSE_BITFS, "   BOWSER'S FLYING FUCKING FORTRESS")
SECRET_STAR(COURSE_BITS, "   BOWSER IN THE SKY")
SECRET_STAR(COURSE_PSS, "   THE PRINCESS'S SECRET SLIDE")
SECRET_STAR(COURSE_COTMC, "   CAVERN OF THE METAL CAP")
SECRET_STAR(COURSE_TOTWC, "   TOWER OF THE WING CAP")
SECRET_STAR(COURSE_VCUTM, "   VANISH CAP UNDER THE MOAT")
SECRET_STAR(COURSE_WMOTR, "   WING MARIO OVER THE RAINBOW")
SECRET_STAR(COURSE_SA, "   THE SECRET AQUARIUM")
SECRET_STAR(COURSE_CAKE_END, "")

CASTLE_SECRET_STARS("   CASTLE SECRET STARS")

EXTRA_TEXT(0, "ONE OF THE CASTLE'S SECRET STARS!")
EXTRA_TEXT(1, "")
EXTRA_TEXT(2, "")
EXTRA_TEXT(3, "")
EXTRA_TEXT(4, "")
EXTRA_TEXT(5, "")
EXTRA_TEXT(6, "")
