#include "src/game/envfx_snow.h"

const GeoLayout strollin_stu_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_CULLING_RADIUS(6971704),
		GEO_OPEN_NODE(),
			GEO_SHADOW(1, 150, 100),
			GEO_OPEN_NODE(),
				GEO_SCALE(LAYER_OPAQUE, 16384),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 160, -32, 90, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, strollin_stu_body_mesh),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 128, 0, 138, strollin_stu_foot_L_mesh),
								GEO_ANIMATED_PART(LAYER_OPAQUE, -128, 0, 138, strollin_stu_foot_R_mesh),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, strollin_stu_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
