extern const GeoLayout lightningbolt_sc_opt1[];
extern const GeoLayout lightningbolt_sc_opt2[];
extern const GeoLayout lightningbolt_geo[];
extern Lights1 lightningbolt_lightning1_lights;
extern Lights1 lightningbolt_lightning2_layer5_lights;
extern Lights1 lightningbolt_lightning3_layer5_lights;
extern u8 lightningbolt_lcord_1_ia8[];
extern u8 lightningbolt_lcord_2_ia8[];
extern u8 lightningbolt_lcord_3_ia8[];
extern Vtx lightningbolt_body_mesh_layer_5_vtx_0[4];
extern Gfx lightningbolt_body_mesh_layer_5_tri_0[];
extern Gfx mat_lightningbolt_lightning1[];
extern Gfx mat_revert_lightningbolt_lightning1[];
extern Gfx mat_lightningbolt_lightning2_layer5[];
extern Gfx mat_revert_lightningbolt_lightning2_layer5[];
extern Gfx mat_lightningbolt_lightning3_layer5[];
extern Gfx mat_revert_lightningbolt_lightning3_layer5[];
extern Gfx lightningbolt_body_mesh_layer_5[];
extern Gfx lightningbolt_body_mesh_layer_5_mat_override_lightning2_0[];
extern Gfx lightningbolt_body_mesh_layer_5_mat_override_lightning3_1[];
extern Gfx lightningbolt_material_revert_render_settings[];
