#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "game/level_geo.h"
#include "game/geo_misc.h"
#include "game/camera.h"
#include "game/moving_texture.h"
#include "game/screen_transition.h"
#include "game/paintings.h"

#include "make_const_nonconst.h"

#include "levels/jrb/header.h"

#include "levels/jrb/falling_pillar/geo.inc.c"
#include "levels/jrb/falling_pillar_base/geo.inc.c"
#include "levels/jrb/rock/geo.inc.c"
#include "levels/jrb/floating_platform/geo.inc.c"
#include "levels/jrb/sliding_box/geo.inc.c"
#include "levels/jrb/wooden_ship/geo.inc.c"
#include "levels/jrb/areas/1/geo.inc.c"
#include "levels/jrb/areas/2/geo.inc.c"
#include "levels/jrb/geo.inc.c"

#include "levels/jrb/carousel/geo.inc.c"
#include "levels/jrb/circus_pole/geo.inc.c"
#include "levels/jrb/clown_clock/geo.inc.c"
#include "levels/jrb/clown_door_top/geo.inc.c"
#include "levels/jrb/clown_door_bottom/geo.inc.c"
#include "levels/jrb/cable_car/geo.inc.c"
#include "levels/jrb/circus_balloon/geo.inc.c"
#include "levels/jrb/pinwheel/geo.inc.c"
#include "levels/jrb/trapeze/geo.inc.c"
#include "levels/jrb/balloon_platform/geo.inc.c"
#include "levels/jrb/clown_boss/geo.inc.c"
#include "levels/jrb/boss_curtains/geo.inc.c"
#include "levels/jrb/steel_gate/geo.inc.c"
#include "levels/jrb/sad_carousel/geo.inc.c"
#include "levels/jrb/sad_pinwheel/geo.inc.c"
#include "levels/jrb/sad_clown_clock/geo.inc.c"
#include "levels/jrb/power_switch/geo.inc.c"
#include "levels/jrb/kid_toad/geo.inc.c"
#include "levels/jrb/clown_toad/geo.inc.c"
#include "levels/jrb/circus_wheel/geo.inc.c"
#include "levels/jrb/circus_cannon/geo.inc.c"