#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "game/level_geo.h"
#include "game/geo_misc.h"
#include "game/camera.h"
#include "game/moving_texture.h"
#include "game/screen_transition.h"
#include "game/paintings.h"

#include "make_const_nonconst.h"

#include "levels/jrb/header.h"

#include "levels/jrb/falling_pillar/geo.inc.c"
#include "levels/jrb/falling_pillar_base/geo.inc.c"
#include "levels/jrb/rock/geo.inc.c"
#include "levels/jrb/floating_platform/geo.inc.c"
#include "levels/jrb/sliding_box/geo.inc.c"
#include "levels/jrb/wooden_ship/geo.inc.c"
#include "levels/jrb/areas/1/geo.inc.c"
#include "levels/jrb/areas/2/geo.inc.c"
#include "levels/jrb/geo.inc.c"

#include "carousel/geo.inc.c"
#include "circus_pole/geo.inc.c"
#include "clown_clock/geo.inc.c"
#include "clown_door_top/geo.inc.c"
#include "clown_door_bottom/geo.inc.c"
#include "circus_wheel/geo.inc.c"
#include "cable_car/geo.inc.c"
#include "circus_balloon/geo.inc.c"
#include "pinwheel/geo.inc.c"
#include "trapeze/geo.inc.c"
#include "balloon_platform/geo.inc.c"
#include "clown_boss/geo.inc.c"
#include "boss_curtains/geo.inc.c"
#include "steel_gate/geo.inc.c"
#include "sad_carousel/geo.inc.c"
#include "sad_pinwheel/geo.inc.c"
#include "sad_clown_clock/geo.inc.c"
#include "power_switch/geo.inc.c"
#include "kid_toad/geo.inc.c"
#include "clown_toad/geo.inc.c"