#include "src/game/envfx_snow.h"

const GeoLayout wf_palm_bits_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, wf_palm_tree_bits_mid_stem_skinned_mesh_layer_1),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 500, 0, wf_palm_tree_bits_mid_stem_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, wf_palm_tree_bits_leaf_002_skinned_mesh_layer_4),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 12, 516, -7, 0, -62, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, wf_palm_tree_bits_leaf_002_mesh_layer_4),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, wf_palm_tree_bits_leaf_003_skinned_mesh_layer_4),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 12, 516, 7, 0, -119, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, wf_palm_tree_bits_leaf_003_mesh_layer_4),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, wf_palm_tree_bits_leaf_004_skinned_mesh_layer_4),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 1, 516, 11, 0, 178, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, wf_palm_tree_bits_leaf_004_mesh_layer_4),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, wf_palm_tree_bits_leaf_005_skinned_mesh_layer_4),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -10, 516, 6, 0, 117, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, wf_palm_tree_bits_leaf_005_mesh_layer_4),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, wf_palm_tree_bits_leaf_006_skinned_mesh_layer_4),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -8, 516, -5, 0, 57, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, wf_palm_tree_bits_leaf_006_mesh_layer_4),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, wf_palm_tree_bits_leaf_1_skinned_mesh_layer_4),
				GEO_ANIMATED_PART(LAYER_ALPHA, 0, 516, -10, wf_palm_tree_bits_leaf_1_mesh_layer_4),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, wf_palm_tree_bits_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, wf_palm_tree_bits_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
