extern const GeoLayout fwoosh_button_geo[];
extern u8 fwoosh_button_i8_metal_pattern2_i8[];
extern Vtx fwoosh_button_buttondl_mesh_layer_2_vtx_0[8];
extern Gfx fwoosh_button_buttondl_mesh_layer_2_tri_0[];
extern Vtx fwoosh_button_buttondl_mesh_layer_1_vtx_0[12];
extern Gfx fwoosh_button_buttondl_mesh_layer_1_tri_0[];
extern Gfx mat_fwoosh_button_MetalDecal[];
extern Gfx mat_revert_fwoosh_button_MetalDecal[];
extern Gfx mat_fwoosh_button_MetalGlow[];
extern Gfx mat_revert_fwoosh_button_MetalGlow[];
extern Gfx fwoosh_button_buttondl_mesh_layer_2[];
extern Gfx fwoosh_button_buttondl_mesh_layer_1[];
extern Gfx fwoosh_button_material_revert_render_settings[];
