extern const GeoLayout lightning_bolt_geo[];
extern Lights1 lightning_bolt_Billboard_lights;
extern Lights1 lightning_bolt_Yellow_lights;
extern Vtx lightning_bolt_bb_mesh_layer_5_vtx_0[10];
extern Gfx lightning_bolt_bb_mesh_layer_5_tri_0[];
extern Vtx lightning_bolt_bolt_mesh_layer_1_vtx_0[6];
extern Gfx lightning_bolt_bolt_mesh_layer_1_tri_0[];
extern Gfx mat_lightning_bolt_Billboard[];
extern Gfx mat_revert_lightning_bolt_Billboard[];
extern Gfx mat_lightning_bolt_Yellow[];
extern Gfx mat_revert_lightning_bolt_Yellow[];
extern Gfx lightning_bolt_bb_mesh_layer_5[];
extern Gfx lightning_bolt_bolt_mesh_layer_1[];
extern Gfx lightning_bolt_material_revert_render_settings[];
