#include "src/game/envfx_snow.h"

const GeoLayout nipper_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_SHADOW(1, 150, 400),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 23, 0, nipper_stem_mesh),
					GEO_OPEN_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 179, 7, 89, 0, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, nipper_HeadLow_mesh),
						GEO_CLOSE_NODE(),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 189, 7, -89, 180, 0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, nipper_HeadUp_mesh),
							GEO_OPEN_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 120, 3, -89, -180, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, nipper_eyes_mesh),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, nipper_leaf1L_skinned),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 53, 17, 0, 0, 0, -73),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, nipper_leaf1L_mesh),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, nipper_leaf2L_skinned),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 50, 0, 0, 0, -39),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, nipper_leaf2L_mesh),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(LAYER_OPAQUE, nipper_leaf1R_skinned),
						GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -52, 17, 0, 0, 0, 73),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, nipper_leaf1R_mesh),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(LAYER_OPAQUE, nipper_leaf2R_skinned),
								GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 50, 0, 0, 0, 39),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, nipper_leaf2R_mesh),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, nipper_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, nipper_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
