extern const GeoLayout ttc_area_1_geo[];
extern const GeoLayout ttc_area_1[];
extern const Collision ttc_area_1_collision[];
extern const MacroObject ttc_area_1_macro_objs[];
extern Lights1 ttc_dl_f3d_material_lights;
extern Vtx ttc_dl_Plane_001_mesh_layer_1_vtx_cull[8];
extern Vtx ttc_dl_Plane_001_mesh_layer_1_vtx_0[4];
extern Gfx ttc_dl_Plane_001_mesh_layer_1_tri_0[];
extern Gfx mat_ttc_dl_f3d_material[];
extern Gfx ttc_dl_Plane_001_mesh_layer_1[];
extern Gfx ttc_dl_material_revert_render_settings[];
