#include "levels/ddd/cozy_warp_pad/texscroll.inc.h"
#include "levels/ddd/water_plane2_ctrl_room/texscroll.inc.h"
#include "levels/ddd/water_plane1/texscroll.inc.h"
#include "levels/ddd/water_switch/texscroll.inc.h"
#include "levels/ddd/shyguy_scuba/texscroll.inc.h"
#include "levels/ddd/cloud/texscroll.inc.h"
#include "levels/ddd/water_spout/texscroll.inc.h"
#include "levels/ddd/water_top/texscroll.inc.h"
#include "levels/ddd/texscroll.inc.h"
extern void scroll_textures_ddd();
