extern const GeoLayout bowser_3_area_1_geo[];
extern const GeoLayout bowser_3_area_1[];
extern const Collision bowser_3_area_1_collision[];
extern const MacroObject bowser_3_area_1_macro_objs[];
extern Lights1 bowser_3_dl_floor_lights;
extern Lights1 bowser_3_dl_bricks_lights;
extern Lights1 bowser_3_dl_gate_lights;
extern u8 bowser_3_dl_Bricks_3_ci8[];
extern u8 bowser_3_dl_Bricks_3_ci8_pal_rgba16[];
extern u8 bowser_3_dl_brickci4_ci4[];
extern u8 bowser_3_dl_brickci4_ci4_pal_rgba16[];
extern u8 bowser_3_dl_bob_gate_ci4[];
extern u8 bowser_3_dl_bob_gate_ci4_pal_rgba16[];
extern Vtx bowser_3_dl_nocol_mesh_layer_1_vtx_0[76];
extern Gfx bowser_3_dl_nocol_mesh_layer_1_tri_0[];
extern Vtx bowser_3_dl_op_mesh_layer_1_vtx_0[1026];
extern Gfx bowser_3_dl_op_mesh_layer_1_tri_0[];
extern Vtx bowser_3_dl_op_mesh_layer_1_vtx_1[374];
extern Gfx bowser_3_dl_op_mesh_layer_1_tri_1[];
extern Vtx bowser_3_dl_op_mesh_layer_4_vtx_0[80];
extern Gfx bowser_3_dl_op_mesh_layer_4_tri_0[];
extern Gfx mat_bowser_3_dl_floor[];
extern Gfx mat_revert_bowser_3_dl_floor[];
extern Gfx mat_bowser_3_dl_bricks[];
extern Gfx mat_revert_bowser_3_dl_bricks[];
extern Gfx mat_bowser_3_dl_gate[];
extern Gfx mat_revert_bowser_3_dl_gate[];
extern Gfx bowser_3_dl_nocol_mesh_layer_1[];
extern Gfx bowser_3_dl_op_mesh_layer_1[];
extern Gfx bowser_3_dl_op_mesh_layer_4[];
extern Gfx bowser_3_dl_material_revert_render_settings[];
