extern const GeoLayout bowser_3_area_1_geo[];
extern const GeoLayout bowser_3_area_1[];
extern const Collision bowser_3_area_1_collision[];
extern const MacroObject bowser_3_area_1_macro_objs[];
extern Lights1 bowser_3_dl_f3dlite_material_lights;
extern Vtx bowser_3_dl_Circle_mesh_layer_1_vtx_0[40];
extern Gfx bowser_3_dl_Circle_mesh_layer_1_tri_0[];
extern Gfx mat_bowser_3_dl_f3dlite_material[];
extern Gfx bowser_3_dl_Circle_mesh_layer_1[];
extern Gfx bowser_3_dl_material_revert_render_settings[];
