#include "src/game/envfx_snow.h"

const GeoLayout chain_chomp_bowser_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 0x96, 200),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 180, -90, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ASM(0, geo_cc_set_prim_color),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, chain_chomp_bowser_000_offset_001_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, chain_chomp_bowser_001_offset_mesh_layer_1),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 0, 0, 180, -90, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, chain_chomp_bowser_000_offset_002_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, chain_chomp_bowser_001_offset_001_mesh_layer_1),
						GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, chain_chomp_bowser_002_offset_001_mesh_layer_4),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, chain_chomp_bowser_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, chain_chomp_bowser_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
