extern const GeoLayout bounce_cloud_geo[];
extern Lights1 bounce_cloud_Cloud_001_lights;
extern u8 bounce_cloud_clouds_i8_i8[];
extern u8 bounce_cloud_smiling_face_ia8[];
extern Vtx bounce_cloud_Cloud_001_mesh_layer_1_vtx_cull[8];
extern Vtx bounce_cloud_Cloud_001_mesh_layer_1_vtx_0[29];
extern Gfx bounce_cloud_Cloud_001_mesh_layer_1_tri_0[];
extern Vtx bounce_cloud_Cloud_001_mesh_layer_5_vtx_cull[8];
extern Vtx bounce_cloud_Cloud_001_mesh_layer_5_vtx_0[4];
extern Gfx bounce_cloud_Cloud_001_mesh_layer_5_tri_0[];
extern Gfx mat_bounce_cloud_Cloud_001[];
extern Gfx mat_bounce_cloud_SmileFace[];
extern Gfx bounce_cloud_Cloud_001_mesh_layer_1[];
extern Gfx bounce_cloud_Cloud_001_mesh_layer_5[];
extern Gfx bounce_cloud_material_revert_render_settings[];
