#include "levels/pss/area_1/geo.inc.c"
#include "levels/pss/area_2/geo.inc.c"
#include "levels/pss/area_3/geo.inc.c"
#include "levels/pss/area_4/geo.inc.c"
#include "levels/pss/area_5/geo.inc.c"
#include "levels/pss/area_7/geo.inc.c"
