#include <ultra64.h>
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "level_misc_macros.h"
#include "macro_preset_names.h"
#include "special_preset_names.h"
#include "textures.h"
#include "dialog_ids.h"

#include "make_const_nonconst.h"
#include "levels/pss/texture.inc.c"
#include "levels/pss/areas/1/1/model.inc.c"
#include "levels/pss/areas/1/2/model.inc.c"
#include "levels/pss/areas/1/3/model.inc.c"
#include "levels/pss/areas/1/4/model.inc.c"
#include "levels/pss/areas/1/5/model.inc.c"
#include "levels/pss/areas/1/6/model.inc.c"
#include "levels/pss/areas/1/7/model.inc.c"
#include "levels/pss/areas/1/collision.inc.c"
#include "levels/pss/areas/1/macro.inc.c"

#include "levels/pss/leveldata.inc.c"

#include "levels/pss/warpbox_pss/model.inc.c"

#include "levels/pss/clown_door_bottom_pss/model.inc.c"
#include "levels/pss/clown_door_bottom_pss/collision.inc.c"
#include "levels/pss/clown_door_top_pss/model.inc.c"
#include "levels/pss/clown_door_top_pss/collision.inc.c"
#include "levels/pss/carousel_pss/model.inc.c"
#include "levels/pss/carousel_pss/collision.inc.c"
#include "levels/pss/carousel_pss/anims/data.inc.c"
#include "levels/pss/carousel_pss/anims/table.inc.c"
#include "levels/pss/balloon_platform_pss/model.inc.c"
#include "levels/pss/balloon_platform_pss/collision.inc.c"
#include "levels/pss/pinwheel_pss/model.inc.c"
#include "levels/pss/circus_balloon_pss/model.inc.c"
#include "levels/pss/circus_balloon_pss/collision.inc.c"
#include "levels/pss/trapeze_pss/model.inc.c"
#include "levels/pss/clown_clock_pss/model.inc.c"
#include "levels/pss/clown_clock_pss/collision.inc.c"

#include "levels/pss/pss_octagonal_platform/model.inc.c"
#include "levels/pss/pss_octagonal_platform/collision.inc.c"