extern const GeoLayout bbh_area_1_geo[];
extern const GeoLayout bbh_area_1[];
extern const Collision bbh_area_1_collision[];
extern const MacroObject bbh_area_1_macro_objs[];
extern Lights1 bbh_dl_Cloud_lights;
extern Lights1 bbh_dl_Clouds_lights;
extern Lights1 bbh_dl_Metal_lights;
extern Lights1 bbh_dl_Metal2_lights;
extern u8 bbh_dl_clouds_i8_i8[];
extern u8 bbh_dl_clouds4_i8_i8[];
extern u8 bbh_dl_i8_metal_pattern2_i8[];
extern u8 bbh_dl_i8_metal_texture_i8[];
extern Vtx bbh_dl_Cloud_mesh_layer_1_vtx_cull[8];
extern Vtx bbh_dl_Cloud_mesh_layer_1_vtx_0[29];
extern Gfx bbh_dl_Cloud_mesh_layer_1_tri_0[];
extern Vtx bbh_dl_Clouds_mesh_layer_1_vtx_cull[8];
extern Vtx bbh_dl_Clouds_mesh_layer_1_vtx_0[174];
extern Gfx bbh_dl_Clouds_mesh_layer_1_tri_0[];
extern Vtx bbh_dl_Metal_mesh_layer_1_vtx_cull[8];
extern Vtx bbh_dl_Metal_mesh_layer_1_vtx_0[12];
extern Gfx bbh_dl_Metal_mesh_layer_1_tri_0[];
extern Vtx bbh_dl_Metal_001_mesh_layer_1_vtx_cull[8];
extern Vtx bbh_dl_Metal_001_mesh_layer_1_vtx_0[12];
extern Gfx bbh_dl_Metal_001_mesh_layer_1_tri_0[];
extern Gfx mat_bbh_dl_Cloud[];
extern Gfx mat_bbh_dl_Clouds[];
extern Gfx mat_revert_bbh_dl_Clouds[];
extern Gfx mat_bbh_dl_Metal[];
extern Gfx mat_revert_bbh_dl_Metal[];
extern Gfx mat_bbh_dl_Metal2[];
extern Gfx mat_revert_bbh_dl_Metal2[];
extern Gfx bbh_dl_Cloud_mesh_layer_1[];
extern Gfx bbh_dl_Clouds_mesh_layer_1[];
extern Gfx bbh_dl_Metal_mesh_layer_1[];
extern Gfx bbh_dl_Metal_001_mesh_layer_1[];
extern Gfx bbh_dl_material_revert_render_settings[];
