#include "src/game/envfx_snow.h"

const GeoLayout bitdw_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(1, 0, -1490, 0, bitdw_dl_Cube_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 6842, 1685, -11550, bitdw_dl_final_pipe_torus_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 12440, -3172, 8466, bitdw_dl_final_platforms_right_side_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 8302, -4498, 8620, bitdw_dl_first_torus_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_NODE_WITH_DL(1, 2451, -1510, 2744, bitdw_dl_first_walljumps_right_side_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(1, 1308, -3328, -954, bitdw_dl_gateway_cube_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(5, 568, -2290, 934, bitdw_dl_mid_platform_mesh_layer_5),
			GEO_TRANSLATE_NODE_WITH_DL(1, 397, -3515, -1601, bitdw_dl_slide_block_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(1, 1256, -4027, 0, bitdw_dl_start_platform_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(1, 1912, -2290, 2895, bitdw_dl_start_platform_right_side_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(1, 1527, -2867, -1740, bitdw_dl_wall_jump_block_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(1, 1282, -2108, 0, bitdw_dl_walljumps_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(1, 6842, -305, -4497, bitdw_dl_forth_torus_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 5362, -1569, 6347, bitdw_dl_second_torus_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 2202, -3252, -629, bitdw_dl_third_torus_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bitdw_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_GREEN_SKY, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, bitdw_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(1, bitdw_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, bitdw_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
