#include "src/game/envfx_snow.h"

const GeoLayout bitdw_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(3, geo_switch_area),
		GEO_OPEN_NODE(),
			GEO_BRANCH(1, bitdw_dl_B_geo),
			GEO_BRANCH(1, bitdw_dl_C_geo),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(1, 0, -1490, 0, bitdw_dl_Cube_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bitdw_dl_B_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(1, 3207, -4583, 7151, bitdw_dl_Cone_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(5, 3650, -4403, 10104, bitdw_dl_Cube_004_mesh_layer_5),
		GEO_TRANSLATE_NODE_WITH_DL(1, 12440, -3172, 8466, bitdw_dl_final_platforms_right_side_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 8302, -4498, 8620, bitdw_dl_first_torus_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_TRANSLATE_NODE_WITH_DL(1, 2451, -1510, 2744, bitdw_dl_first_walljumps_right_side_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(1, 1308, -3328, -954, bitdw_dl_gateway_cube_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(5, 568, -2290, 934, bitdw_dl_mid_platform_mesh_layer_5),
			GEO_TRANSLATE_NODE_WITH_DL(1, 1256, -4027, 0, bitdw_dl_start_platform_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(1, 1912, -2290, 2895, bitdw_dl_start_platform_right_side_mesh_layer_1),
			GEO_TRANSLATE_NODE_WITH_DL(1, 1282, -2108, 0, bitdw_dl_walljumps_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(1, 6842, -305, -4497, bitdw_dl_forth_torus_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 0, -372, -922, bitdw_dl_pipe_1_final_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(5, -3883, -6582, -2395, bitdw_dl_pipe_1_final_001_mesh_layer_5),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(1, bitdw_dl_pipe_1_final_001_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(1, 0, -372, -922, bitdw_dl_pipe_entrance_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 5362, -1569, 6347, bitdw_dl_second_torus_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(5, 4890, -7350, 9456, bitdw_dl_TOWER_mesh_layer_5),
		GEO_TRANSLATE_NODE_WITH_DL(5, 4890, -7350, 9456, bitdw_dl_TOWER_001_mesh_layer_5),
		GEO_TRANSLATE_NODE_WITH_DL(5, 5362, -1569, 6347, bitdw_dl_water_bottom_mesh_layer_5),
		GEO_TRANSLATE_NODE_WITH_DL(1, 5519, -1418, 6331, bitdw_dl_water_top_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(5, 5617, -1505, 6295, bitdw_dl_water_top_fake_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bitdw_dl_C_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(1, 0, -372, -922, bitdw_dl_pipe_1_final_room_2_mesh_layer_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bitdw_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_GREEN_SKY, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, bitdw_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(1, bitdw_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, bitdw_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
