extern const GeoLayout bitfs_area_1_geo[];
extern const GeoLayout bitfs_area_1[];
extern const Collision bitfs_area_1_collision[];
extern const MacroObject bitfs_area_1_macro_objs[];
extern Lights1 bitfs_dl_snow_lights;
extern Lights1 bitfs_dl_grass_lights;
extern Lights1 bitfs_dl_dirt_lights;
extern Lights1 bitfs_dl_darksnow_lights;
extern Lights1 bitfs_dl_icewall_lights;
extern u8 bitfs_dl_krtd_ice_floor_ci4[];
extern u8 bitfs_dl_krtd_ice_floor_ci4_pal_rgba16[];
extern u8 bitfs_dl_z_midori_ci8[];
extern u8 bitfs_dl_z_midori_ci8_pal_rgba16[];
extern u8 bitfs_dl_cavewall_ci4[];
extern u8 bitfs_dl_cavewall_ci4_pal_rgba16[];
extern u8 bitfs_dl_krtd_ice_floor_dark_ci4[];
extern u8 bitfs_dl_krtd_ice_floor_dark_ci4_pal_rgba16[];
extern u8 bitfs_dl_ice_kabe_ci4[];
extern u8 bitfs_dl_ice_kabe_ci4_pal_rgba16[];
extern Vtx bitfs_dl_nocol_mesh_layer_1_vtx_0[179];
extern Gfx bitfs_dl_nocol_mesh_layer_1_tri_0[];
extern Vtx bitfs_dl_nocol_mesh_layer_1_vtx_1[135];
extern Gfx bitfs_dl_nocol_mesh_layer_1_tri_1[];
extern Vtx bitfs_dl_nocol_mesh_layer_1_vtx_2[46];
extern Gfx bitfs_dl_nocol_mesh_layer_1_tri_2[];
extern Vtx bitfs_dl_op_mesh_layer_1_vtx_0[126];
extern Gfx bitfs_dl_op_mesh_layer_1_tri_0[];
extern Vtx bitfs_dl_op_mesh_layer_1_vtx_1[30];
extern Gfx bitfs_dl_op_mesh_layer_1_tri_1[];
extern Vtx bitfs_dl_op_mesh_layer_1_vtx_2[6];
extern Gfx bitfs_dl_op_mesh_layer_1_tri_2[];
extern Gfx mat_bitfs_dl_snow[];
extern Gfx mat_revert_bitfs_dl_snow[];
extern Gfx mat_bitfs_dl_grass[];
extern Gfx mat_revert_bitfs_dl_grass[];
extern Gfx mat_bitfs_dl_dirt[];
extern Gfx mat_revert_bitfs_dl_dirt[];
extern Gfx mat_bitfs_dl_darksnow[];
extern Gfx mat_revert_bitfs_dl_darksnow[];
extern Gfx mat_bitfs_dl_icewall[];
extern Gfx mat_revert_bitfs_dl_icewall[];
extern Gfx bitfs_dl_nocol_mesh_layer_1[];
extern Gfx bitfs_dl_op_mesh_layer_1[];
extern Gfx bitfs_dl_material_revert_render_settings[];
