extern void scroll_water_plane2_ctrl_room_water_plane2_ctrl_room_mesh_layer_7_vtx_0();
extern void scroll_sts_mat_water_plane2_ctrl_room_foggy_wahwah_layer7();
extern void scroll_ddd_level_geo_water_plane2_ctrl_room();
