#include "src/game/envfx_snow.h"

const GeoLayout ddd_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 0, -4000, 0),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 0, -4000, 0, ddd_dl_Cube_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(LAYER_OPAQUE, 0, -4000, 0, ddd_dl_TunnelBetween_mesh_layer_1),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE, 0, -4000, 0),
		GEO_OPEN_NODE(),
			GEO_ASM(LAYER_TRANSPARENT_DECAL, geo_set_water_lights),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, ddd_dl_WaterSideDecal_mesh_layer_6),
		GEO_CLOSE_NODE(),
		GEO_ASM(0, geo_backdrop_move_cozies),
		GEO_TRANSLATE_NODE(LAYER_OPAQUE_INTER, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ASM((0x0A << 8) | LAYER_OPAQUE_INTER, geo_mountain_fog),
			GEO_DISPLAY_LIST(LAYER_OPAQUE_INTER, ddd_dl_A_Front_Mountains_mesh_layer_3),
			GEO_ASM((0x30 << 8) | LAYER_OPAQUE_INTER, geo_mountain_fog),
			GEO_DISPLAY_LIST(LAYER_OPAQUE_INTER, ddd_dl_A_ZABack_Mountains_001_mesh_layer_3),
			GEO_ASM((0x30 << 8) | LAYER_OPAQUE_INTER, geo_mountain_fog),
			GEO_DISPLAY_LIST(LAYER_OPAQUE_INTER, ddd_dl_A_ZBack_Mountains_mesh_layer_3),
			GEO_DISPLAY_LIST(LAYER_OPAQUE_INTER, ddd_dl_ZZSkyOcean_mesh_layer_3),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout ddd_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, ddd_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_SNOW_WATER, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, ddd_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_OPAQUE_INTER, ddd_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT_DECAL, ddd_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
