#include "src/game/envfx_snow.h"

const GeoLayout clown_boss_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, clown_boss_Root_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 100, 0, clown_boss_Torso_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 68, 0, clown_boss_Chest_mesh_layer_1),
				GEO_OPEN_NODE(),
					GEO_ASM(0, geo_clown_head_scaler),
					GEO_SCALE_BETTER(LAYER_OPAQUE, 65536, 65536, 65536),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 114, 0, clown_boss_Head_geo_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_clown_head_scaler),
							GEO_SCALE_BETTER(LAYER_OPAQUE, 65536, 65536, 65536),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, -35, 83, 79, clown_boss_eyeleft_geo_mesh_layer_1),
							GEO_CLOSE_NODE(),
							GEO_ASM(0, geo_clown_head_scaler),
							GEO_SCALE_BETTER(LAYER_OPAQUE, 65536, 65536, 65536),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 36, 83, 79, clown_boss_eyeright_geo_mesh_layer_1),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, clown_boss_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
