#include "src/game/envfx_snow.h"

const GeoLayout bbh_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(1, -3208, 193, 13848, bbh_dl_Cloud_mesh_layer_1),
		GEO_DISPLAY_LIST(1, bbh_dl_Clouds_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, -15020, 0, 17160, bbh_dl_Clouds_001_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, -6090, 3, 15737, bbh_dl_Metal_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, -3318, 3, 18254, bbh_dl_Metal_001_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, -13516, 1238, 15335, bbh_dl_PrisonWalls_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, -9347, 193, 11008, bbh_dl_RainCloud_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(5, bbh_dl_RainCloud_mesh_layer_5),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bbh_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND(BACKGROUND_OCEAN_SKY, geo_skybox_main),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -100, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, bbh_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(1, bbh_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, bbh_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
