extern const GeoLayout ddd_area_1_geo[];
extern const GeoLayout ddd_area_1[];
extern const Collision ddd_area_1_collision[];
extern const MacroObject ddd_area_1_macro_objs[];
extern u8 ddd_dl_dirty_homes_i8[];
extern u8 ddd_dl_water_big_chungus_defined_intensity2_i4[];
extern u8 ddd_dl_water_pls_try_sharper_intensity2_i4[];
extern Vtx ddd_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx ddd_dl_Cube_mesh_layer_1_vtx_0[79];
extern Gfx ddd_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx ddd_dl_WaterSideDecal_mesh_layer_6_vtx_cull[8];
extern Vtx ddd_dl_WaterSideDecal_mesh_layer_6_vtx_0[22];
extern Gfx ddd_dl_WaterSideDecal_mesh_layer_6_tri_0[];
extern Vtx ddd_dl_ZPlane_mesh_layer_3_vtx_cull[8];
extern Vtx ddd_dl_ZPlane_mesh_layer_3_vtx_0[41];
extern Gfx ddd_dl_ZPlane_mesh_layer_3_tri_0[];
extern Vtx ddd_dl_ZZCube_001_mesh_layer_7_vtx_cull[8];
extern Vtx ddd_dl_ZZCube_001_mesh_layer_7_vtx_0[14];
extern Gfx ddd_dl_ZZCube_001_mesh_layer_7_tri_0[];
extern Gfx mat_ddd_dl_base_layer1[];
extern Gfx mat_revert_ddd_dl_base_layer1[];
extern Gfx mat_ddd_dl_waterdecal_layer6[];
extern Gfx mat_revert_ddd_dl_waterdecal_layer6[];
extern Gfx mat_ddd_dl_groundypoo_layer3[];
extern Gfx mat_revert_ddd_dl_groundypoo_layer3[];
extern Gfx mat_ddd_dl_f3d_material_001_layer7[];
extern Gfx mat_revert_ddd_dl_f3d_material_001_layer7[];
extern Gfx ddd_dl_Cube_mesh_layer_1[];
extern Gfx ddd_dl_WaterSideDecal_mesh_layer_6[];
extern Gfx ddd_dl_ZPlane_mesh_layer_3[];
extern Gfx ddd_dl_ZZCube_001_mesh_layer_7[];
extern Gfx ddd_dl_material_revert_render_settings[];
