#include <ultra64.h>
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "level_misc_macros.h"
#include "macro_preset_names.h"
#include "special_preset_names.h"
#include "textures.h"
#include "dialog_ids.h"

#include "make_const_nonconst.h"
// #include "levels/ddd/texture.inc.c"
// #include "levels/ddd/areas/1/1/model.inc.c"
// #include "levels/ddd/areas/1/2/model.inc.c"
// #include "levels/ddd/areas/1/3/model.inc.c"
// #include "levels/ddd/areas/1/4/model.inc.c"
// #include "levels/ddd/areas/2/1/model.inc.c"
// #include "levels/ddd/areas/2/2/model.inc.c"
// #include "levels/ddd/areas/2/3/model.inc.c"
// #include "levels/ddd/areas/2/4/model.inc.c"
// #include "levels/ddd/sub_door/1.inc.c"
// #include "levels/ddd/sub_door/2.inc.c"
// #include "levels/ddd/sub_door/3.inc.c"
// #include "levels/ddd/submarine/1.inc.c"
// #include "levels/ddd/submarine/2.inc.c"
// #include "levels/ddd/areas/2/5/model.inc.c"
// #include "levels/ddd/areas/2/6/model.inc.c"
// #include "levels/ddd/pole/model.inc.c"
// #include "levels/ddd/areas/1/collision.inc.c"
// #include "levels/ddd/areas/2/collision.inc.c"
// #include "levels/ddd/areas/1/macro.inc.c"
// #include "levels/ddd/areas/2/macro.inc.c"
// #include "levels/ddd/submarine/collision.inc.c"
// #include "levels/ddd/sub_door/collision.inc.c"
// #include "levels/ddd/areas/1/movtext.inc.c"
// #include "levels/ddd/areas/2/movtext.inc.c"

#include "levels/ddd/leveldata.inc.c"

#include "levels/ddd/cloud/model.inc.c"
#include "levels/ddd/cloud/collision.inc.c"
#include "levels/ddd/water_top/collision.inc.c"
#include "levels/ddd/water_top/model.inc.c"
#include "levels/ddd/frames/frames.inc.c"
#include "levels/ddd/misc_vars/misc_vars.inc.c"

#include "levels/ddd/water_spout/model.inc.c"
#include "levels/ddd/water_spout/collision.inc.c"
#include "levels/ddd/aperature_door/model.inc.c"
#include "levels/ddd/aperature_door/collision.inc.c"
#include "levels/ddd/aperature_door/anims/data.inc.c"
#include "levels/ddd/aperature_door/anims/table.inc.c"
#include "levels/ddd/floaty_rock/model.inc.c"
#include "levels/ddd/floaty_rock/collision.inc.c"
#include "levels/ddd/shyguy_scuba/model.inc.c"
#include "levels/ddd/water_switch/collision.inc.c"
#include "levels/ddd/water_switch/model.inc.c"
#include "levels/ddd/flippy_bitch/model.inc.c"
#include "levels/ddd/flippy_bitch/collision.inc.c"

#include "levels/ddd/water_plane1/collision.inc.c"
#include "levels/ddd/water_plane1/model.inc.c"

#include "levels/ddd/water_plane2_ctrl_room/model.inc.c"
#include "levels/ddd/water_plane2_ctrl_room/collision.inc.c"
#include "levels/ddd/water_plane3_purp_room/collision.inc.c"
#include "levels/ddd/water_plane3_purp_room/model.inc.c"
#include "levels/ddd/tube_top/model.inc.c"
#include "levels/ddd/tube_top/collision.inc.c"
#include "levels/ddd/water_plane4_whirlpool/collision.inc.c"
#include "levels/ddd/water_plane4_whirlpool/model.inc.c"
#include "levels/ddd/the_20_coin/model.inc.c"